/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Codex (GPT-6-Sol).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

#define FX_SOURCE_CODE

#include "fx_api.h"
#include "fx_media.h"
#include "fx_utility.h"

/* Update the primary boot-sector dirty marker without changing other fields.  */
static UINT  _fx_media_FAT32_boot_mark(FX_MEDIA *media_ptr, UCHAR *buffer_ptr, UINT clean)
{
    media_ptr -> fx_media_driver_request =      FX_DRIVER_BOOT_READ;
    media_ptr -> fx_media_driver_status =       FX_IO_ERROR;
    media_ptr -> fx_media_driver_buffer =       buffer_ptr;
    media_ptr -> fx_media_driver_sectors =      1;
    media_ptr -> fx_media_driver_sector_type =  FX_BOOT_SECTOR;
    (media_ptr -> fx_media_driver_entry)(media_ptr);
    if (media_ptr -> fx_media_driver_status != FX_SUCCESS)
    {
        return(FX_IO_ERROR);
    }

    if (clean)
    {
        buffer_ptr[65] =  (UCHAR)(buffer_ptr[65] & (UCHAR)~1U);
    }
    else
    {
        buffer_ptr[65] =  (UCHAR)(buffer_ptr[65] | 1U);
    }

    media_ptr -> fx_media_driver_request =       FX_DRIVER_BOOT_WRITE;
    media_ptr -> fx_media_driver_status =        FX_IO_ERROR;
    media_ptr -> fx_media_driver_system_write =  FX_TRUE;
    (media_ptr -> fx_media_driver_entry)(media_ptr);
    media_ptr -> fx_media_driver_system_write =  FX_FALSE;
    if (media_ptr -> fx_media_driver_status != FX_SUCCESS)
    {
        return(FX_IO_ERROR);
    }

    return(FX_SUCCESS);
}

/* Set the FAT32 clean-shutdown markers while preserving the other FAT bits.  */
UINT  _fx_media_FAT32_clean_set(FX_MEDIA *media_ptr, UINT clean)
{
UCHAR *buffer_ptr;
ULONG  entry;
ULONG  sector;
UINT   fat_index;
UINT   copy_index;
UINT   status;

#ifndef FX_DISABLE_CACHE
    buffer_ptr =  media_ptr -> fx_media_sector_cache_list_ptr -> fx_cached_sector_memory_buffer;
    media_ptr -> fx_media_sector_cache_list_ptr -> fx_cached_sector =  (~(ULONG64)0);
    media_ptr -> fx_media_sector_cache_list_ptr -> fx_cached_sector_valid =  FX_FALSE;
#else
    buffer_ptr =  media_ptr -> fx_media_memory_buffer;
    media_ptr -> fx_media_memory_buffer_sector =  (ULONG64)-1;
#endif

    /* Clear the boot marker before the primary FAT can become clean.  */
    if (clean)
    {
        status =  _fx_media_FAT32_boot_mark(media_ptr, buffer_ptr, clean);
        if (status != FX_SUCCESS)
        {
            return(status);
        }
    }

    for (fat_index = 0; fat_index < media_ptr -> fx_media_number_of_FATs; fat_index++)
    {
        /* The primary FAT is the first dirty and last clean copy.  */
        copy_index =  clean ? (fat_index + 1U) % media_ptr -> fx_media_number_of_FATs : fat_index;
        sector =  media_ptr -> fx_media_reserved_sectors +
                   (copy_index * media_ptr -> fx_media_sectors_per_FAT);

        media_ptr -> fx_media_driver_request =          FX_DRIVER_READ;
        media_ptr -> fx_media_driver_status =           FX_IO_ERROR;
        media_ptr -> fx_media_driver_buffer =           buffer_ptr;
        media_ptr -> fx_media_driver_logical_sector =   sector;
        media_ptr -> fx_media_driver_sectors =          1;
        media_ptr -> fx_media_driver_sector_type =      FX_FAT_SECTOR;
        (media_ptr -> fx_media_driver_entry)(media_ptr);
        if (media_ptr -> fx_media_driver_status != FX_SUCCESS)
        {
            return(FX_IO_ERROR);
        }

        entry =  _fx_utility_32_unsigned_read(&buffer_ptr[4]);
        if (clean)
        {
            entry |=  0x08000000UL;
        }
        else
        {
            entry &=  ~0x08000000UL;
        }
        _fx_utility_32_unsigned_write(&buffer_ptr[4], entry);

        media_ptr -> fx_media_driver_request =       FX_DRIVER_WRITE;
        media_ptr -> fx_media_driver_status =        FX_IO_ERROR;
        media_ptr -> fx_media_driver_system_write =  FX_TRUE;
        (media_ptr -> fx_media_driver_entry)(media_ptr);
        media_ptr -> fx_media_driver_system_write =  FX_FALSE;
        if (media_ptr -> fx_media_driver_status != FX_SUCCESS)
        {
            return(FX_IO_ERROR);
        }
    }

    /* A dirty FAT remains visible if the boot-sector write fails.  */
    if (clean == FX_FALSE)
    {
        status =  _fx_media_FAT32_boot_mark(media_ptr, buffer_ptr, clean);
        if (status != FX_SUCCESS)
        {
            return(status);
        }
    }

    media_ptr -> fx_media_driver_request =  FX_DRIVER_FLUSH;
    media_ptr -> fx_media_driver_status =   FX_IO_ERROR;
    (media_ptr -> fx_media_driver_entry)(media_ptr);
    if (media_ptr -> fx_media_driver_status != FX_SUCCESS)
    {
        return(FX_IO_ERROR);
    }

    return(FX_SUCCESS);
}
