/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Codex (GPT-6).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

#include "fx_api.h"
#include <string.h>

#define TEST_SECTOR_SIZE              512u
#define TEST_PARTITION_OFFSET         446u
#define TEST_PARTITION_TYPE_OFFSET    4u
#define TEST_PARTITION_START_OFFSET   8u
#define TEST_PARTITION_SIZE_OFFSET    12u

extern UINT _fx_partition_offset_calculate_extended(FX_MEDIA *media_ptr, void *partition_sector,
                                                     UINT partition, ULONG *partition_start,
                                                     ULONG *partition_size);
void test_control_return(UINT status);
void test_application_define(void *first_unused_memory);

typedef enum TEST_DRIVER_MODE_ENUM
{
    TEST_DRIVER_SUCCESS,
    TEST_DRIVER_READ_ERROR,
    TEST_DRIVER_BAD_SIGNATURE,
    TEST_DRIVER_EMPTY_PARTITION,
    TEST_DRIVER_CHAIN
} TEST_DRIVER_MODE;

static TEST_DRIVER_MODE test_driver_mode;

/* Supply an extended boot record or a controlled read error.  */
static void test_partition_driver(FX_MEDIA *media_ptr)
{
UCHAR *sector;

    if (test_driver_mode == TEST_DRIVER_READ_ERROR)
    {
        media_ptr->fx_media_driver_status = FX_IO_ERROR;
        return;
    }

    sector = (UCHAR *)media_ptr->fx_media_driver_buffer;
    (void)memset(sector, 0, TEST_SECTOR_SIZE);
    sector[510] = (UCHAR)0x55;
    sector[511] = (UCHAR)0xAA;
    if (test_driver_mode == TEST_DRIVER_BAD_SIGNATURE)
    {
        sector[510] = (UCHAR)0;
    }
    if (test_driver_mode != TEST_DRIVER_EMPTY_PARTITION)
    {
        sector[TEST_PARTITION_OFFSET + TEST_PARTITION_TYPE_OFFSET] = (UCHAR)0x0B;
        sector[TEST_PARTITION_OFFSET + TEST_PARTITION_START_OFFSET] = (UCHAR)3;
        sector[TEST_PARTITION_OFFSET + TEST_PARTITION_SIZE_OFFSET] = (UCHAR)9;
    }
    if (test_driver_mode == TEST_DRIVER_CHAIN)
    {
        if (media_ptr->fx_media_driver_logical_sector == (ULONG)7)
        {
            sector[TEST_PARTITION_OFFSET + 16u + TEST_PARTITION_TYPE_OFFSET] = (UCHAR)0x05;
            sector[TEST_PARTITION_OFFSET + 16u + TEST_PARTITION_START_OFFSET] = (UCHAR)20;
        }
        else
        {
            sector[TEST_PARTITION_OFFSET + TEST_PARTITION_START_OFFSET] = (UCHAR)4;
        }
    }
    media_ptr->fx_media_driver_status = FX_SUCCESS;
}

/* Verify boot records, primary partitions, and extended partition reads.  */
void test_application_define(void *first_unused_memory)
{
FX_MEDIA media = {0};
UCHAR sector[TEST_SECTOR_SIZE] = {0};
ULONG start = 0;
ULONG size = 0;
UINT status;

    FX_PARAMETER_NOT_USED(first_unused_memory);

    sector[0] = (UCHAR)0xEB;
    sector[2] = (UCHAR)0x90;
    sector[0x16] = (UCHAR)1;
    sector[0x13] = (UCHAR)0x34;
    sector[0x14] = (UCHAR)0x12;
    status = _fx_partition_offset_calculate_extended(&media, sector, 0, &start, &size);
    if ((status != FX_SUCCESS) || (start != (ULONG)0) || (size != (ULONG)0x1234))
    {
        test_control_return((UINT)1);
        return;
    }

    sector[0x13] = (UCHAR)0;
    sector[0x14] = (UCHAR)0;
    sector[0x20] = (UCHAR)0x78;
    sector[0x21] = (UCHAR)0x56;
    status = _fx_partition_offset_calculate_extended(&media, sector, 0, FX_NULL, &size);
    if ((status != FX_SUCCESS) || (size != (ULONG)0x5678))
    {
        test_control_return((UINT)2);
        return;
    }

    (void)memset(sector, 0, sizeof(sector));
    status = _fx_partition_offset_calculate_extended(&media, sector, 0, &start, &size);
    if (status != FX_NOT_FOUND)
    {
        test_control_return((UINT)12);
        return;
    }
    sector[510] = (UCHAR)0x55;
    sector[511] = (UCHAR)0xAA;
    sector[TEST_PARTITION_OFFSET + TEST_PARTITION_TYPE_OFFSET] = (UCHAR)0x0B;
    sector[TEST_PARTITION_OFFSET + TEST_PARTITION_START_OFFSET] = (UCHAR)7;
    sector[TEST_PARTITION_OFFSET + TEST_PARTITION_SIZE_OFFSET] = (UCHAR)9;
    status = _fx_partition_offset_calculate_extended(&media, sector, 0, &start, &size);
    if ((status != FX_SUCCESS) || (start != (ULONG)7) || (size != (ULONG)9))
    {
        test_control_return((UINT)3);
        return;
    }
    status = _fx_partition_offset_calculate_extended(&media, sector, 0, FX_NULL, FX_NULL);
    if (status != FX_SUCCESS)
    {
        test_control_return((UINT)4);
        return;
    }
    sector[TEST_PARTITION_OFFSET + TEST_PARTITION_TYPE_OFFSET] = (UCHAR)0;
    status = _fx_partition_offset_calculate_extended(&media, sector, 0, &start, &size);
    if (status != FX_NOT_FOUND)
    {
        test_control_return((UINT)13);
        return;
    }
    sector[TEST_PARTITION_OFFSET + TEST_PARTITION_TYPE_OFFSET] = (UCHAR)0x0B;
    status = _fx_partition_offset_calculate_extended(&media, sector, 17, &start, &size);
    if (status != FX_NOT_FOUND)
    {
        test_control_return((UINT)5);
        return;
    }
    status = _fx_partition_offset_calculate_extended(&media, sector, 4, &start, &size);
    if (status != FX_NOT_FOUND)
    {
        test_control_return((UINT)6);
        return;
    }

    sector[TEST_PARTITION_OFFSET + TEST_PARTITION_TYPE_OFFSET] = (UCHAR)0x05;
    media.fx_media_driver_entry = test_partition_driver;
    test_driver_mode = TEST_DRIVER_SUCCESS;
    status = _fx_partition_offset_calculate_extended(&media, sector, 5, &start, &size);
    if (status != FX_NOT_FOUND)
    {
        test_control_return((UINT)14);
        return;
    }
    (void)memset(sector, 0, sizeof(sector));
    sector[510] = (UCHAR)0x55;
    sector[511] = (UCHAR)0xAA;
    sector[TEST_PARTITION_OFFSET + TEST_PARTITION_TYPE_OFFSET] = (UCHAR)0x05;
    sector[TEST_PARTITION_OFFSET + TEST_PARTITION_START_OFFSET] = (UCHAR)7;
    status = _fx_partition_offset_calculate_extended(&media, sector, 4, &start, &size);
    if ((status != FX_SUCCESS) || (start != (ULONG)10) || (size != (ULONG)9))
    {
        test_control_return((UINT)7);
        return;
    }

    test_driver_mode = TEST_DRIVER_READ_ERROR;
    (void)memset(sector, 0, sizeof(sector));
    sector[510] = (UCHAR)0x55;
    sector[511] = (UCHAR)0xAA;
    sector[TEST_PARTITION_OFFSET + TEST_PARTITION_TYPE_OFFSET] = (UCHAR)0x05;
    sector[TEST_PARTITION_OFFSET + TEST_PARTITION_START_OFFSET] = (UCHAR)7;
    status = _fx_partition_offset_calculate_extended(&media, sector, 4, &start, &size);
    if (status != FX_IO_ERROR)
    {
        test_control_return((UINT)8);
        return;
    }
    test_driver_mode = TEST_DRIVER_BAD_SIGNATURE;
    status = _fx_partition_offset_calculate_extended(&media, sector, 4, &start, &size);
    if (status != FX_NOT_FOUND)
    {
        test_control_return((UINT)9);
        return;
    }
    test_driver_mode = TEST_DRIVER_EMPTY_PARTITION;
    sector[510] = (UCHAR)0x55;
    sector[TEST_PARTITION_OFFSET + TEST_PARTITION_TYPE_OFFSET] = (UCHAR)0x05;
    sector[TEST_PARTITION_OFFSET + TEST_PARTITION_START_OFFSET] = (UCHAR)7;
    status = _fx_partition_offset_calculate_extended(&media, sector, 4, &start, &size);
    if (status != FX_NOT_FOUND)
    {
        test_control_return((UINT)10);
        return;
    }

    test_driver_mode = TEST_DRIVER_CHAIN;
    sector[510] = (UCHAR)0x55;
    sector[TEST_PARTITION_OFFSET + TEST_PARTITION_TYPE_OFFSET] = (UCHAR)0x05;
    sector[TEST_PARTITION_OFFSET + TEST_PARTITION_START_OFFSET] = (UCHAR)7;
    status = _fx_partition_offset_calculate_extended(&media, sector, 5, &start, &size);
    if ((status != FX_SUCCESS) || (start != (ULONG)31) || (size != (ULONG)9))
    {
        test_control_return((UINT)11);
        return;
    }

    test_control_return((UINT)0);
}
