/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 * 
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 * 
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 * 
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* This FileX test turns ThreadX event tracing on and establishes that the FileX trace
   shims then do their work: that _fx_trace_event_insert hands back a live trace entry and
   that _fx_trace_event_update writes to it.

   Nothing else in the suite enables tracing.  _tx_trace_buffer_current_ptr is therefore
   null on every call the other tests make, _fx_trace_event_insert returns FX_NULL without
   recording anything, and _fx_trace_event_update finds no event to update -- which is why
   the bodies of both shims sit uncovered even in the one configuration that compiles them.
   The assertions below state that starting condition and then remove it.

   No symbol is replaced and no state is manufactured.  tx_trace_enable is a public ThreadX
   service and an application may call it at any time; the buffer it is handed here is the
   test's own memory.

   The two knobs are the trace buffer size and the registry entry count.  A buffer sized to
   lap within a single FileX operation is what reaches the shims' overwrite arms, and that
   belongs to the trace coverage work rather than here.

   The test asserts only where the shims exist.  fx_api.h remaps FX_TRACE_IN_LINE_INSERT
   and FX_TRACE_EVENT_UPDATE onto them under TX_ENABLE_EVENT_TRACE && !FX_STANDALONE_ENABLE
   and nowhere else, so one of the eleven build configurations compiles the code under test
   and the other ten take the N/A arm.  */

#ifndef FX_STANDALONE_ENABLE
#include   "tx_api.h"
#endif
#include   "fx_api.h"
#include   "fx_ram_driver_test.h"
#include   <stdio.h>

void  test_control_return(UINT status);

#if defined(TX_ENABLE_EVENT_TRACE) && !defined(FX_STANDALONE_ENABLE)

#define     DEMO_STACK_SIZE         4096
#define     CACHE_SIZE              128*128
#define     SECTOR_SIZE             128
#define     TOTAL_SECTORS           256

#define     TEST_SECTOR             100

/* The trace buffer holds the control header, the object registry and the event log.  It is
   declared as ULONG so that it is aligned for the entries carved out of it.  */

#define     TRACE_REGISTRY_ENTRIES  16
#define     TRACE_BUFFER_LONGS      (16 * 1024)


/* Define the ThreadX and FileX object control blocks...  */

static TX_THREAD               ftest_0;
static FX_MEDIA                ram_disk;

static ULONG                   trace_buffer[TRACE_BUFFER_LONGS];
static UCHAR                   raw_sector_buffer[SECTOR_SIZE];


/* Define the counters used in the test application...  */

static UCHAR                  *ram_disk_memory;
static UCHAR                  *cache_buffer;


/* Define thread prototypes.  */

void    filex_trace_enable_application_define(void *first_unused_memory);
static void    ftest_0_entry(ULONG thread_input);

VOID  _fx_ram_driver(FX_MEDIA *media_ptr);


/* Define what the initial system looks like.  */

#ifdef CTEST
void test_application_define(void *first_unused_memory)
#else
void    filex_trace_enable_application_define(void *first_unused_memory)
#endif
{

UCHAR    *pointer;


    /* Setup the working pointer.  */
    pointer =  (UCHAR *) first_unused_memory;

    /* Create the main thread.  */
    tx_thread_create(&ftest_0, "thread 0", ftest_0_entry, 0,  
            pointer, DEMO_STACK_SIZE, 
            4, 4, TX_NO_TIME_SLICE, TX_AUTO_START);

    pointer =  pointer + DEMO_STACK_SIZE;

    /* Setup memory for the RAM disk and the sector cache.  */
    cache_buffer =  pointer;
    pointer =  pointer + CACHE_SIZE;
    ram_disk_memory =  pointer;

    /* Initialize the FileX system.  */
    fx_system_initialize();
}


/* Find the first recorded event carrying this event id.  */

static TX_TRACE_BUFFER_ENTRY  *find_event(ULONG event_id)
{

TX_TRACE_BUFFER_ENTRY   *entry;

    for (entry = _tx_trace_buffer_start_ptr; entry < _tx_trace_buffer_end_ptr; entry++)
    {
        if (entry -> tx_trace_buffer_entry_event_id == event_id)
        {
            return(entry);
        }
    }

    return(FX_NULL);
}


/* Find the first recorded event carrying this event id and this fourth information field.
   The fourth field of a media read or write event is written only by the post-event update,
   so a match is evidence that _fx_trace_event_update ran against a live entry.  */

static TX_TRACE_BUFFER_ENTRY  *find_updated_event(ULONG event_id, ULONG info_field_4)
{

TX_TRACE_BUFFER_ENTRY   *entry;

    for (entry = _tx_trace_buffer_start_ptr; entry < _tx_trace_buffer_end_ptr; entry++)
    {
        if ((entry -> tx_trace_buffer_entry_event_id == event_id) &&
            (entry -> tx_trace_buffer_entry_information_field_4 == info_field_4))
        {
            return(entry);
        }
    }

    return(FX_NULL);
}


/* Define the test threads.  */

static void    ftest_0_entry(ULONG thread_input)
{

UINT        status;

    FX_PARAMETER_NOT_USED(thread_input);

    /* Print out some test information banners.  */
    printf("FileX Test:   Trace enable harness test..............................");

    /* Tracing is off until this test turns it on, which is the condition that leaves the
       FileX trace shims unexercised everywhere else.  */
    return_value_if_fail(_tx_trace_buffer_current_ptr == TX_NULL, 1);

    /* Format the media.  This needs to be done before opening it!  */
    status =  fx_media_format(&ram_disk, 
                            _fx_ram_driver,         // Driver entry
                            ram_disk_memory,        // RAM disk memory pointer
                            cache_buffer,           // Media buffer pointer
                            CACHE_SIZE,             // Media buffer size 
                            "MY_RAM_DISK",          // Volume Name
                            1,                      // Number of FATs
                            32,                     // Directory Entries
                            0,                      // Hidden sectors
                            TOTAL_SECTORS,          // Total sectors 
                            SECTOR_SIZE,            // Sector size   
                            1,                      // Sectors per cluster
                            1,                      // Heads
                            1);                     // Sectors per track 
    return_value_if_fail(status == FX_SUCCESS, 2);

    /* Open the RAM disk.  */
    status =  fx_media_open(&ram_disk, "RAM DISK", _fx_ram_driver, ram_disk_memory, cache_buffer, CACHE_SIZE);
    return_value_if_fail(status == FX_SUCCESS, 3);

    /* Enable event tracing into the test's own buffer.  */
    status =  tx_trace_enable(trace_buffer, sizeof(trace_buffer), TRACE_REGISTRY_ENTRIES);
    return_value_if_fail(status == TX_SUCCESS, 4);

    /* Tracing is on, so the shims now have somewhere to record.  */
    return_value_if_fail(_tx_trace_buffer_current_ptr != TX_NULL, 5);
    return_value_if_fail(_tx_trace_buffer_start_ptr < _tx_trace_buffer_end_ptr, 6);

    /* Drive one public read and one public write.  */
    status =  fx_media_write(&ram_disk, TEST_SECTOR, (VOID *) raw_sector_buffer);
    return_value_if_fail(status == FX_SUCCESS, 7);

    status =  fx_media_read(&ram_disk, TEST_SECTOR, (VOID *) raw_sector_buffer);
    return_value_if_fail(status == FX_SUCCESS, 8);

    /* The API events reached the trace buffer, so _fx_trace_event_insert recorded them.  */
    return_value_if_fail(find_event(FX_TRACE_MEDIA_READ) != FX_NULL, 9);
    return_value_if_fail(find_event(FX_TRACE_MEDIA_WRITE) != FX_NULL, 10);

    /* So did the internal driver events, which is the call site shape most of common/src
       uses.  */
    return_value_if_fail(find_event(FX_TRACE_INTERNAL_IO_DRIVER_READ) != FX_NULL, 11);
    return_value_if_fail(find_event(FX_TRACE_INTERNAL_IO_DRIVER_WRITE) != FX_NULL, 12);

    /* Both API events carry the byte count in their fourth information field, which is
       written only by the post-event update.  _fx_trace_event_insert therefore handed back
       a live entry and _fx_trace_event_update wrote to it.  */
    return_value_if_fail(find_updated_event(FX_TRACE_MEDIA_READ,
                                            ram_disk.fx_media_bytes_per_sector) != FX_NULL, 13);
    return_value_if_fail(find_updated_event(FX_TRACE_MEDIA_WRITE,
                                            ram_disk.fx_media_bytes_per_sector) != FX_NULL, 14);

    /* Close the media.  */
    status =  fx_media_close(&ram_disk);
    return_value_if_fail(status == FX_SUCCESS, 15);

    printf("SUCCESS!\n");
    test_control_return(0);
}

#else
#ifdef CTEST
void test_application_define(void *first_unused_memory)
#else
void    filex_trace_enable_application_define(void *first_unused_memory)
#endif
{

    FX_PARAMETER_NOT_USED(first_unused_memory);

    /* Print out some test information banners.  */
    printf("FileX Test:   Trace enable harness test..............................N/A\n");

    test_control_return(255);
}
#endif
