/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 * 
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 * 
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 * 
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* This FileX test covers the two constructs in the logical sector paths that only a build
   with the sector cache disabled compiles, and that a run of that build does not otherwise
   reach.

   The first is the whole body of _fx_utility_logical_sector_cache_entry_read.  With
   FX_DISABLE_CACHE defined the function is reduced to returning a null pointer, and all
   four of its call sites -- every one of them inside a region the same macro removes --
   are compiled away with the cache they belong to.  So no shipped configuration calls it:
   the four builds that compile the stub are exactly the four that compile away every
   caller.  A test may call it directly under the practice this branch follows for a
   certified internal function with no caller in the configuration under test.  It is
   declared by common/inc/fx_utility.h, which this file includes, and the media handed to
   it is an ordinary open media rather than a hand-built control block.

   The second needs no direct call.  Without a sector cache the reader keeps the last
   single sector it read in the media's own memory buffer, and short-circuits a repeat
   read of that same sector rather than going back to the driver.  The guard it does that
   behind also asks for exactly one sector, and the arm where that second test fails is a
   multi-sector read whose first sector is the one already held.  fx_file_read produces
   both halves on its own: a read of exactly one sector's worth is served through the
   media memory buffer, which is what records the sector, and a longer read from the same
   offset is issued as one multi-sector request starting at it.

   Nothing is interposed and no state is manufactured.  No symbol is replaced, every
   function on both paths runs its own code end to end, and the media is one fx_media_open
   produced.

   FX_DISABLE_CACHE is what puts both constructs in the build, so the test asserts in the
   four configurations that define it and is reported N/A in the other seven.  */

#ifndef FX_STANDALONE_ENABLE
#include   "tx_api.h"
#endif
#include   "fx_api.h"
#include   "fx_utility.h"
#include   "fx_ram_driver_test.h"
#include   <stdio.h>

void  test_control_return(UINT status);
void  filex_utility_no_cache_sector_test_application_define(void *first_unused_memory);

#ifdef FX_DISABLE_CACHE

#define     DEMO_STACK_SIZE         4096
#define     CACHE_SIZE              2048
#define     SECTOR_SIZE             256
#define     SECTORS_PER_CLUSTER     8
#define     TOTAL_SECTORS           256

/* Two sectors of file is all the multi-sector read needs, and a third keeps the read from
   being the whole file.  */
#define     FILE_SECTORS            4
#define     FILE_SIZE               (SECTOR_SIZE * FILE_SECTORS)

/* A sector number no media of this size has, so the stub is asked for something that
   could not be in a cache even if there were one.  */
#define     ABSENT_SECTOR           ((ULONG64) 1000)

/* A value the stub must not write through, so that "untouched" is checkable.  */
#define     PREVIOUS_SENTINEL       ((FX_CACHED_SECTOR *) 0x5A5A5A5A)


/* Define the ThreadX and FileX object control blocks...  */

#ifndef FX_STANDALONE_ENABLE
static TX_THREAD               ftest_0;
#endif
static FX_MEDIA                ram_disk;
static FX_FILE                 my_file;


/* Define the counters used in the test application...  */

#ifndef FX_STANDALONE_ENABLE
static UCHAR                  *cache_buffer;
#else
static UCHAR                   cache_buffer[CACHE_SIZE];
#endif

static UCHAR                   data_buffer[FILE_SIZE];


/* Define thread prototypes.  */

static void    ftest_0_entry(ULONG thread_input);

VOID  _fx_ram_driver(FX_MEDIA *media_ptr);


/* Define what the initial system looks like.  */

#ifdef CTEST
void test_application_define(void *first_unused_memory)
#else
void    filex_utility_no_cache_sector_test_application_define(void *first_unused_memory)
#endif
{

#ifndef FX_STANDALONE_ENABLE
UCHAR    *pointer;


    /* Setup the working pointer.  */
    pointer =  (UCHAR *) first_unused_memory;

    /* Create the main thread.  */
    tx_thread_create(&ftest_0, "thread 0", ftest_0_entry, 0,  
            pointer, DEMO_STACK_SIZE, 
            4, 4, TX_NO_TIME_SLICE, TX_AUTO_START);

    pointer =  pointer + DEMO_STACK_SIZE;

    /* Setup memory for the sector cache.  */
    cache_buffer =  pointer;

#else
    FX_PARAMETER_NOT_USED(first_unused_memory);
#endif

    /* Initialize the FileX system.  */
    fx_system_initialize();
#ifdef FX_STANDALONE_ENABLE
    ftest_0_entry(0);
#endif
}


/* Define the test threads.  */

static void    ftest_0_entry(ULONG thread_input)
{

UINT                 status;
ULONG                actual;
ULONG                i;
FX_CACHED_SECTOR    *entry;
FX_CACHED_SECTOR    *previous;
ULONG64              held_sector;


    FX_PARAMETER_NOT_USED(thread_input);

    /* Print out some test information banners.  */
    printf("FileX Test:   Utility no cache sector test...........................");

    /* Format the media.  This needs to be done before opening it!  */
    status =  fx_media_format(&ram_disk, 
                            _fx_ram_driver,         // Driver entry
                            ram_disk_memory_large,  // RAM disk memory pointer
                            cache_buffer,           // Media buffer pointer
                            CACHE_SIZE,             // Media buffer size 
                            "MY_RAM_DISK",          // Volume Name
                            1,                      // Number of FATs
                            32,                     // Directory Entries
                            0,                      // Hidden sectors
                            TOTAL_SECTORS,          // Total sectors 
                            SECTOR_SIZE,            // Sector size   
                            SECTORS_PER_CLUSTER,    // Sectors per cluster
                            1,                      // Heads
                            1);                     // Sectors per track 
    return_value_if_fail(status == FX_SUCCESS, 1);

    /* Open the RAM disk.  */
    status =  fx_media_open(&ram_disk, "RAM DISK", _fx_ram_driver, ram_disk_memory_large, cache_buffer, CACHE_SIZE);
    return_value_if_fail(status == FX_SUCCESS, 2);


    /* ---- The cache entry reader with no cache to read ------------------------------
       There is no cache in this build, so the function has nothing to look in and says so
       by returning a null pointer, whatever it is asked for.  It is asked twice: once for
       a sector the media holds and once for a sector past the end of it, because a stub
       that answered one and not the other would not be a stub.  The caller's output
       pointer is left alone in both cases.  */

    previous =  PREVIOUS_SENTINEL;
    entry =  _fx_utility_logical_sector_cache_entry_read(&ram_disk, (ULONG64) 1, &previous);
    return_value_if_fail(entry == FX_NULL, 3);
    return_value_if_fail(previous == PREVIOUS_SENTINEL, 4);

    previous =  PREVIOUS_SENTINEL;
    entry =  _fx_utility_logical_sector_cache_entry_read(&ram_disk, ABSENT_SECTOR, &previous);
    return_value_if_fail(entry == FX_NULL, 5);
    return_value_if_fail(previous == PREVIOUS_SENTINEL, 6);


    /* ---- A multi-sector read starting at the sector already held --------------------  */

    for (i = 0; i < FILE_SIZE; i++)
    {
        data_buffer[i] =  (UCHAR) i;
    }

    status =  fx_file_create(&ram_disk, "NOCACHE.TXT");
    return_value_if_fail(status == FX_SUCCESS, 7);

    status =  fx_file_open(&ram_disk, &my_file, "NOCACHE.TXT", FX_OPEN_FOR_WRITE);
    return_value_if_fail(status == FX_SUCCESS, 8);

    status =  fx_file_write(&my_file, data_buffer, FILE_SIZE);
    return_value_if_fail(status == FX_SUCCESS, 9);

    status =  fx_file_close(&my_file);
    return_value_if_fail(status == FX_SUCCESS, 10);

    status =  fx_file_open(&ram_disk, &my_file, "NOCACHE.TXT", FX_OPEN_FOR_READ);
    return_value_if_fail(status == FX_SUCCESS, 11);

    /* Exactly one sector.  fx_file_read takes its single-sector arm, which reads through
       the media memory buffer, and that is what records the sector the buffer holds.  */
    status =  fx_file_read(&my_file, data_buffer, SECTOR_SIZE, &actual);
    return_value_if_fail(status == FX_SUCCESS, 12);
    return_value_if_fail(actual == SECTOR_SIZE, 13);

    held_sector =  ram_disk.fx_media_memory_buffer_sector;
    return_value_if_fail(held_sector != (ULONG64) -1, 14);

    /* Back to the beginning, then a read long enough to be issued as one multi-sector
       request.  Its first sector is the one the memory buffer is still holding, so the
       reader's short-circuit is entered and refused on the sector count rather than on the
       sector number.  */
    status =  fx_file_seek(&my_file, 0);
    return_value_if_fail(status == FX_SUCCESS, 15);

    status =  fx_file_read(&my_file, data_buffer, SECTOR_SIZE * 2, &actual);
    return_value_if_fail(status == FX_SUCCESS, 16);
    return_value_if_fail(actual == (SECTOR_SIZE * 2), 17);

    /* The read was served from the medium rather than short-circuited, so both sectors
       carry what was written.  */
    for (i = 0; i < (SECTOR_SIZE * 2); i++)
    {
        return_value_if_fail(data_buffer[i] == (UCHAR) i, 18);
    }

    /* The second read started at the sector the first one left in the buffer, which is
       what says the first operand of that guard was true.  */
    return_value_if_fail(held_sector == ram_disk.fx_media_memory_buffer_sector, 19);

    status =  fx_file_close(&my_file);
    return_value_if_fail(status == FX_SUCCESS, 20);

    /* Close the media.  */
    status =  fx_media_close(&ram_disk);
    return_value_if_fail(status == FX_SUCCESS, 21);

    printf("SUCCESS!\n");
    test_control_return(0);
}

#else
#ifdef CTEST
void test_application_define(void *first_unused_memory)
#else
void    filex_utility_no_cache_sector_test_application_define(void *first_unused_memory)
#endif
{

    FX_PARAMETER_NOT_USED(first_unused_memory);

    /* Print out some test information banners.  */
    printf("FileX Test:   Utility no cache sector test...........................N/A\n");

    test_control_return(255);
}
#endif
