/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 * 
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 * 
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 * 
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* This FileX test covers the arms of the two trace shims that an ordinary traced run
   never reaches, and the two system getters whose trace guard exists only in a trace
   build.

   A companion test establishes the starting condition: nothing else in the suite enables
   tracing, so both shims sit idle everywhere.  With tracing on, a plain sequence of FileX
   calls covers the shims' main path and leaves five groups of arms untouched.  Each group
   needs a different lever, and each is set up and asserted separately below.

   The trace buffer is the lever for three of them.  ThreadX carves the caller's buffer
   into a control header, an object registry and an event log, so the number of events the
   log holds is chosen by sizing the buffer.  A log of four entries laps within a single
   FileX operation; a log of one entry is overwritten by every event that follows.

   Nothing is interposed.  No symbol is replaced and no FileX or ThreadX function is
   stubbed: every function on every path below runs its own code end to end.

   Two levers alter state the test then puts back, and both are disclosed here, because a
   test that alters the system under it has to say so in its own file.

   The first is the interrupt nesting count.  _tx_thread_system_state is the Linux port's
   ISR nesting count: tx_thread_context_save.c increments it on every interrupt entry and
   tx_thread_context_restore.c decrements it on exit, so a non-zero value is the state the
   kernel is in on every clock tick.  tx_initialize_kernel_enter.c assigns it
   TX_INITIALIZE_IN_PROGRESS, 0xF0F0F0F0, immediately before it calls tx_application_define,
   so that value is the state the kernel is in throughout initialisation.  The test writes
   each value, issues one traced call, and writes back what it found.  The window is held
   under TX_DISABLE, which takes the port mutex that tx_thread_context_save must also take,
   so the tick cannot observe or change the count while the test has it set -- without that
   lockout the tick's matching decrement could land after the restore.

   The route this replaces was measured rather than assumed.  A ThreadX timer callback was
   the obvious candidate and does not work: TX_TIMER_PROCESS_IN_ISR is not defined by this
   port, so application timer callbacks run in the timer thread with the nesting count at
   zero, which a probe confirmed.  Calling the port's own _tx_thread_context_save cannot be
   used either -- it suspends the calling thread when the count is zero, so a thread that
   called it would suspend itself.

   The second is the direct call, which DEC-governed practice on this branch allows for a
   certified internal function whose shipped callers never present the case under test.
   Three functions are called directly here and the sentence differs for each, so each is
   stated where it is used.  All three are declared by a header -- _fx_trace_event_insert
   and _fx_trace_event_update by common/inc/fx_api.h under FX_SOURCE_CODE, which is why the
   prototypes are repeated below, and _fx_system_date_get and _fx_system_time_get by
   common/inc/fx_system.h, which this file includes.  None of them is undeclared.

   The test asserts only where the shims exist.  fx_api.h remaps FX_TRACE_IN_LINE_INSERT and
   FX_TRACE_EVENT_UPDATE onto them under TX_ENABLE_EVENT_TRACE && !FX_STANDALONE_ENABLE and
   nowhere else, so one of the eleven build configurations compiles the code under test and
   the other ten take the N/A arm.  */

#ifndef FX_STANDALONE_ENABLE
#include   "tx_api.h"
#endif
#include   "fx_api.h"
#include   "fx_system.h"
#include   "fx_ram_driver_test.h"
#include   <stdio.h>

void  test_control_return(UINT status);
void  filex_trace_shim_coverage_test_application_define(void *first_unused_memory);

#if defined(TX_ENABLE_EVENT_TRACE) && !defined(FX_STANDALONE_ENABLE)

/* fx_api.h declares both shims under FX_SOURCE_CODE, which a test does not define, so the
   prototypes are repeated here.  They are copied from common/inc/fx_api.h.  */

VOID _fx_trace_event_insert(ULONG event_id, ULONG info_field_1, ULONG info_field_2,
                            ULONG info_field_3, ULONG info_field_4, ULONG filter,
                            TX_TRACE_BUFFER_ENTRY **current_event, ULONG *current_timestamp);
VOID _fx_trace_event_update(TX_TRACE_BUFFER_ENTRY *event, ULONG timestamp, ULONG event_id,
                            ULONG info_field_1, ULONG info_field_2, ULONG info_field_3,
                            ULONG info_field_4);

/* The Linux port's interrupt nesting count.  */
extern volatile ULONG   _tx_thread_system_state;

#define     DEMO_STACK_SIZE         4096
#define     CACHE_SIZE              128*128
#define     SECTOR_SIZE             128
#define     TOTAL_SECTORS           256

#define     TEST_SECTOR             100

/* The value tx_initialize_kernel_enter.c holds the nesting count at while the kernel is
   initialising, and the value the insert macro classifies as "not an interrupt".  */
#define     INITIALIZE_IN_PROGRESS  0xF0F0F0F0UL

/* The macro stamps this into the thread pointer of an event recorded from an interrupt,
   and the sentinel above into the thread pointer of one recorded during initialisation.
   Both are how the recorded entry says which arm ran.  */
#define     RECORDED_FROM_ISR       0xFFFFFFFFUL

/* Information field values chosen so that a match cannot be a coincidence.  No FileX call
   site passes either field, so nothing else can write them.  */
#define     INFO_FIELD_1_VALUE      0x5A5A1111UL
#define     INFO_FIELD_2_VALUE      0xA5A52222UL

/* A trace buffer holds the control header, the object registry and the event log.  These
   two are sized by the number of events their log has to hold.  */
#define     LAP_BUFFER_EVENTS       4
#define     ONE_BUFFER_EVENTS       1
#define     TRACE_BUFFER_BYTES(n)   (sizeof(TX_TRACE_HEADER) +                            \
                                     sizeof(TX_TRACE_OBJECT_ENTRY) +                      \
                                     ((n) * sizeof(TX_TRACE_BUFFER_ENTRY)))

/* Enough activity to lap a four-entry log many times over.  */
#define     LAP_INSERTS             20


/* Define the ThreadX and FileX object control blocks...  */

static TX_THREAD               ftest_0;
static FX_MEDIA                ram_disk;

/* The roomy buffer, for the arms that must not lap.  */
static ULONG                   trace_buffer[16 * 1024];

/* The two sized buffers, ULONG-aligned for the entries carved out of them.  */
static ULONG                   lap_buffer[(TRACE_BUFFER_BYTES(LAP_BUFFER_EVENTS) / sizeof(ULONG)) + 1];
static ULONG                   one_buffer[(TRACE_BUFFER_BYTES(ONE_BUFFER_EVENTS) / sizeof(ULONG)) + 1];

static UCHAR                   raw_sector_buffer[SECTOR_SIZE];


/* Define the counters used in the test application...  */

static UCHAR                  *ram_disk_memory;
static UCHAR                  *cache_buffer;

static ULONG                   full_notify_count;
static ULONG                   registry_entries = 1;


/* Define thread prototypes.  */

static void    ftest_0_entry(ULONG thread_input);

VOID  _fx_ram_driver(FX_MEDIA *media_ptr);


/* Define what the initial system looks like.  */

#ifdef CTEST
void test_application_define(void *first_unused_memory)
#else
void    filex_trace_shim_coverage_test_application_define(void *first_unused_memory)
#endif
{

UCHAR    *pointer;


    /* Setup the working pointer.  */
    pointer =  (UCHAR *) first_unused_memory;

    /* Create the main thread.  */
    tx_thread_create(&ftest_0, "thread 0", ftest_0_entry, 0,  
            pointer, DEMO_STACK_SIZE, 
            4, 4, TX_NO_TIME_SLICE, TX_AUTO_START);

    pointer =  pointer + DEMO_STACK_SIZE;

    /* Setup memory for the RAM disk and the sector cache.  */
    cache_buffer =  pointer;
    pointer =  pointer + CACHE_SIZE;
    ram_disk_memory =  pointer;

    /* Initialize the FileX system.  */
    fx_system_initialize();
}


/* Count the calls ThreadX makes when the event log wraps.  */

static void  full_notify(void *header_ptr)
{

    FX_PARAMETER_NOT_USED(header_ptr);

    full_notify_count++;
}


/* Find the first recorded event carrying this event id.  */

static TX_TRACE_BUFFER_ENTRY  *find_event(ULONG event_id)
{

TX_TRACE_BUFFER_ENTRY   *entry;

    for (entry = _tx_trace_buffer_start_ptr; entry < _tx_trace_buffer_end_ptr; entry++)
    {
        if (entry -> tx_trace_buffer_entry_event_id == event_id)
        {
            return(entry);
        }
    }

    return(FX_NULL);
}


/* Issue one traced FileX call with the interrupt nesting count held at the supplied value,
   and hand back the entry it recorded.  The count is read before the write and put back
   after it, and the whole window runs with interrupts locked out so the clock tick cannot
   change the count while the test has it set.  */

static TX_TRACE_BUFFER_ENTRY  *insert_with_system_state(ULONG state)
{

TX_INTERRUPT_SAVE_AREA

TX_TRACE_BUFFER_ENTRY   *entry;
ULONG                    saved_state;
UINT                     year, month, day;


    TX_DISABLE

    /* The entry the next insert will use.  */
    entry =  _tx_trace_buffer_current_ptr;

    saved_state =  _tx_thread_system_state;
    _tx_thread_system_state =  state;

    /* A getter that inserts an event and needs no media.  */
    _fx_system_date_get(&year, &month, &day);

    _tx_thread_system_state =  saved_state;

    TX_RESTORE

    return(entry);
}


/* Define the test threads.  */

static void    ftest_0_entry(ULONG thread_input)
{

UINT                     status;
UINT                     year, month, day;
UINT                     hour, minute, second;
UINT                     attributes;
ULONG                    i;
TX_TRACE_BUFFER_ENTRY   *entry;
TX_TRACE_BUFFER_ENTRY   *event;
ULONG                    timestamp;
ULONG                    first_timestamp;


    FX_PARAMETER_NOT_USED(thread_input);

    /* Print out some test information banners.  */
    printf("FileX Test:   Trace shim coverage test...............................");

    /* Format the media.  This needs to be done before opening it!  */
    status =  fx_media_format(&ram_disk, 
                            _fx_ram_driver,         // Driver entry
                            ram_disk_memory,        // RAM disk memory pointer
                            cache_buffer,           // Media buffer pointer
                            CACHE_SIZE,             // Media buffer size 
                            "MY_RAM_DISK",          // Volume Name
                            1,                      // Number of FATs
                            32,                     // Directory Entries
                            0,                      // Hidden sectors
                            TOTAL_SECTORS,          // Total sectors 
                            SECTOR_SIZE,            // Sector size   
                            1,                      // Sectors per cluster
                            1,                      // Heads
                            1);                     // Sectors per track 
    return_value_if_fail(status == FX_SUCCESS, 1);

    /* Open the RAM disk.  */
    status =  fx_media_open(&ram_disk, "RAM DISK", _fx_ram_driver, ram_disk_memory, cache_buffer, CACHE_SIZE);
    return_value_if_fail(status == FX_SUCCESS, 2);

    /* Enable event tracing into a buffer roomy enough that nothing below laps it.  */
    status =  tx_trace_enable(trace_buffer, sizeof(trace_buffer), 16);
    return_value_if_fail(status == TX_SUCCESS, 3);
    return_value_if_fail(_tx_trace_buffer_current_ptr != TX_NULL, 4);


    /* ---- The event was recorded from an interrupt ----------------------------------
       The insert macro classifies the nesting count into three cases and stamps the
       recorded entry differently in each.  With the count non-zero and below the
       initialisation sentinel the entry's thread pointer is set to all ones and its
       priority field carries the thread pointer, which is how the recorded entry says
       this arm ran rather than the thread-context one.  */

    entry =  insert_with_system_state(1);
    return_value_if_fail(entry != FX_NULL, 5);
    return_value_if_fail(entry -> tx_trace_buffer_entry_event_id == FX_TRACE_SYSTEM_DATE_GET, 6);
    return_value_if_fail(entry -> tx_trace_buffer_entry_thread_pointer == RECORDED_FROM_ISR, 7);
    return_value_if_fail(entry -> tx_trace_buffer_entry_thread_priority != 0, 8);

    /* The count was put back, so the system is where it was.  */
    return_value_if_fail(_tx_thread_system_state == 0, 9);


    /* ---- The event was recorded during initialisation ------------------------------
       At or above the sentinel the macro stamps the sentinel itself into the thread
       pointer and zeroes the priority, because there is no thread to name yet.  */

    entry =  insert_with_system_state(INITIALIZE_IN_PROGRESS);
    return_value_if_fail(entry != FX_NULL, 10);
    return_value_if_fail(entry -> tx_trace_buffer_entry_event_id == FX_TRACE_SYSTEM_DATE_GET, 11);
    return_value_if_fail(entry -> tx_trace_buffer_entry_thread_pointer == INITIALIZE_IN_PROGRESS, 12);
    return_value_if_fail(entry -> tx_trace_buffer_entry_thread_priority == 0, 13);
    return_value_if_fail(_tx_thread_system_state == 0, 14);


    /* ---- Information fields 1 and 2 ------------------------------------------------
       _fx_trace_event_update is called from 19 sites in common/src, in 13 distinct
       shapes, and not one of them passes a non-zero information field 1 or 2: every call
       site passes 0 for both.  The two guarded assignments for those fields are therefore
       not reachable through any FileX API, and the call below is what reaches them.  The
       entry it updates is one the certified insert produced a moment earlier by the
       ordinary route, and the two arguments are ULONG values rather than state.  */

    _fx_trace_event_insert((ULONG) FX_TRACE_MEDIA_READ, 0, 0, 0, 0,
                           (ULONG) FX_TRACE_MEDIA_EVENTS, &event, &timestamp);
    return_value_if_fail(event != FX_NULL, 15);

    _fx_trace_event_update(event, timestamp, (ULONG) FX_TRACE_MEDIA_READ,
                           INFO_FIELD_1_VALUE, INFO_FIELD_2_VALUE, 0, 0);

    return_value_if_fail(event -> tx_trace_buffer_entry_information_field_1 == INFO_FIELD_1_VALUE, 16);
    return_value_if_fail(event -> tx_trace_buffer_entry_information_field_2 == INFO_FIELD_2_VALUE, 17);


    /* ---- A non-zero information field 3 with a zero field 4 ------------------------
       Three of the 19 call sites pass that pair -- the two attributes reads and the
       best-effort allocate -- so this one needs no direct call.  The attributes of a file
       just created are non-zero and the fourth field is passed as zero, which is the
       combination the remaining two arms of the update need.  */

    status =  fx_file_create(&ram_disk, "TRACE.TXT");
    return_value_if_fail(status == FX_SUCCESS, 18);

    status =  fx_file_attributes_read(&ram_disk, "TRACE.TXT", &attributes);
    return_value_if_fail(status == FX_SUCCESS, 19);
    return_value_if_fail(attributes != 0, 20);

    entry =  find_event(FX_TRACE_FILE_ATTRIBUTES_READ);
    return_value_if_fail(entry != FX_NULL, 21);
    return_value_if_fail(entry -> tx_trace_buffer_entry_information_field_3 == attributes, 22);
    return_value_if_fail(entry -> tx_trace_buffer_entry_information_field_4 == 0, 23);


    /* ---- The two system getters' trace guard ---------------------------------------
       fx_system_date_get and fx_system_time_get guard their insert on all three of their
       arguments being present.  The guard exists only in a trace build: with the insert
       macro expanding to nothing the compiler removes the empty if entirely, which is why
       these arms appear in no other configuration.

       Each function has exactly one caller, its own error-checking shell, and that shell
       rejects a null argument with FX_PTR_ERROR before it calls -- so no shipped
       configuration reaches the guard with an argument missing.  The public name maps to
       the shell in this configuration, and the calls below therefore name the services
       themselves, which common/inc/fx_system.h declares.  The public call is made first
       to show what the shell does with the same arguments.  */

    status =  fx_system_date_get(&year, FX_NULL, FX_NULL);
    return_value_if_fail(status == FX_PTR_ERROR, 24);

    status =  _fx_system_date_get(&year, FX_NULL, FX_NULL);
    return_value_if_fail(status == FX_SUCCESS, 25);

    status =  _fx_system_date_get(&year, &month, FX_NULL);
    return_value_if_fail(status == FX_SUCCESS, 26);

    status =  fx_system_time_get(&hour, FX_NULL, FX_NULL);
    return_value_if_fail(status == FX_PTR_ERROR, 27);

    status =  _fx_system_time_get(&hour, FX_NULL, FX_NULL);
    return_value_if_fail(status == FX_SUCCESS, 28);

    status =  _fx_system_time_get(&hour, &minute, FX_NULL);
    return_value_if_fail(status == FX_SUCCESS, 29);

    /* A complete call still inserts, which is the arm the suite already covers.  */
    status =  _fx_system_date_get(&year, &month, &day);
    return_value_if_fail(status == FX_SUCCESS, 30);
    return_value_if_fail(find_event(FX_TRACE_SYSTEM_DATE_GET) != FX_NULL, 31);


    /* ---- The event was filtered out -------------------------------------------------
       tx_trace_event_filter clears the enable bits for the events named, so the insert
       macro skips its whole body.  The shim picked up an entry pointer before the macro
       ran, finds that entry still carrying whatever was there before, and hands the caller
       a null pointer instead -- which is the arm that tells a caller there is nothing to
       update.  */

    status =  tx_trace_event_filter(FX_TRACE_ALL_EVENTS);
    return_value_if_fail(status == TX_SUCCESS, 32);

    entry =  _tx_trace_buffer_current_ptr;
    _fx_trace_event_insert((ULONG) FX_TRACE_MEDIA_READ, 0, 0, 0, 0,
                           (ULONG) FX_TRACE_MEDIA_EVENTS, &event, &timestamp);

    /* Nothing was recorded, so the shim reported no event and no timestamp.  */
    return_value_if_fail(event == FX_NULL, 33);
    return_value_if_fail(timestamp == 0, 34);
    return_value_if_fail(entry -> tx_trace_buffer_entry_event_id != FX_TRACE_MEDIA_READ, 35);

    /* The insert pointer did not move either.  */
    return_value_if_fail(_tx_trace_buffer_current_ptr == entry, 36);

    status =  tx_trace_event_unfilter(FX_TRACE_ALL_EVENTS);
    return_value_if_fail(status == TX_SUCCESS, 37);

    tx_trace_disable();


    /* ---- The event log wrapped, with no callback registered -------------------------
       A log of four entries wraps every four inserts.  ThreadX resets the insert pointer
       to the start of the log and, when a full-notify callback is registered, calls it.
       Both arms of that test are needed, so the log is lapped twice: once with no callback
       and once with one.  */

    status =  tx_trace_enable(lap_buffer, TRACE_BUFFER_BYTES(LAP_BUFFER_EVENTS), registry_entries);
    return_value_if_fail(status == TX_SUCCESS, 38);
    return_value_if_fail((_tx_trace_buffer_end_ptr - _tx_trace_buffer_start_ptr) == LAP_BUFFER_EVENTS, 39);

    full_notify_count =  0;
    for (i = 0; i < LAP_INSERTS; i++)
    {
        status =  _fx_system_date_get(&year, &month, &day);
        return_value_if_fail(status == FX_SUCCESS, 40);
    }

    /* No callback was registered, so none was called.  */
    return_value_if_fail(full_notify_count == 0, 41);

    tx_trace_disable();


    /* ---- The event log wrapped, with a callback registered --------------------------  */

    status =  tx_trace_enable(lap_buffer, TRACE_BUFFER_BYTES(LAP_BUFFER_EVENTS), registry_entries);
    return_value_if_fail(status == TX_SUCCESS, 42);

    status =  tx_trace_buffer_full_notify(full_notify);
    return_value_if_fail(status == TX_SUCCESS, 43);

    full_notify_count =  0;
    for (i = 0; i < LAP_INSERTS; i++)
    {
        status =  _fx_system_date_get(&year, &month, &day);
        return_value_if_fail(status == FX_SUCCESS, 44);
    }

    /* The log holds four events and far more than four were inserted, so it wrapped and
       the callback was told each time.  */
    return_value_if_fail(full_notify_count > 0, 45);

    tx_trace_buffer_full_notify(TX_NULL);
    tx_trace_disable();


    /* ---- The entry was overwritten before the update reached it ---------------------
       _fx_trace_event_update checks that the entry it was handed still carries the event
       id and the timestamp it had when it was inserted, because the log may have wrapped
       onto it in between.  A log of one entry makes that certain: every event that follows
       lands on the same entry.

       The first case needs no direct call.  fx_media_read inserts its own event, issues
       the driver reads that carry it out -- each of which inserts an internal event onto
       that one entry -- and only then updates.  The entry it goes back to is carrying a
       different event id, so the update declines it.  */

    status =  tx_trace_enable(one_buffer, TRACE_BUFFER_BYTES(ONE_BUFFER_EVENTS), registry_entries);
    return_value_if_fail(status == TX_SUCCESS, 46);
    return_value_if_fail((_tx_trace_buffer_end_ptr - _tx_trace_buffer_start_ptr) == ONE_BUFFER_EVENTS, 47);

    status =  fx_media_write(&ram_disk, TEST_SECTOR, (VOID *) raw_sector_buffer);
    return_value_if_fail(status == FX_SUCCESS, 48);

    status =  fx_media_read(&ram_disk, TEST_SECTOR, (VOID *) raw_sector_buffer);
    return_value_if_fail(status == FX_SUCCESS, 49);

    /* The single entry is carrying an internal driver event rather than the media read,
       and the media read's byte count -- which only the update writes -- never reached it.  */
    entry =  _tx_trace_buffer_start_ptr;
    return_value_if_fail(entry -> tx_trace_buffer_entry_event_id != FX_TRACE_MEDIA_READ, 50);
    return_value_if_fail(entry -> tx_trace_buffer_entry_information_field_4 !=
                         ram_disk.fx_media_bytes_per_sector, 51);


    /* ---- The entry was overwritten by an event of the same id -----------------------
       The remaining arm is the one where the log wrapped a whole lap and the entry carries
       the caller's own event id again, with a later timestamp.  No FileX operation can
       present it: an operation inserts its event once and updates it once, so whatever
       lands on the entry in between always carries a different id -- measured, not
       assumed, with a one-entry log driven by fx_media_read and fx_media_write alone,
       where the different-id arm is taken every time and this one is never reached at all.

       The two inserts below are ordinary calls to the certified insert, which is what
       every FileX trace call site invokes; they produce the entry, both event ids and both
       timestamps.  The test writes nothing into the trace buffer itself.  */

    _fx_trace_event_insert((ULONG) FX_TRACE_MEDIA_READ, 0, 0, 0, 0,
                           (ULONG) FX_TRACE_MEDIA_EVENTS, &event, &timestamp);
    return_value_if_fail(event != FX_NULL, 52);
    first_timestamp =  timestamp;

    /* The same event id again, onto the same single entry.  */
    _fx_trace_event_insert((ULONG) FX_TRACE_MEDIA_READ, 0, 0, 0, 0,
                           (ULONG) FX_TRACE_MEDIA_EVENTS, &event, &timestamp);

    /* The entry now carries the same id and a later timestamp, which is the case under
       test rather than an assumption about it.  */
    entry =  _tx_trace_buffer_start_ptr;
    return_value_if_fail(entry -> tx_trace_buffer_entry_event_id == FX_TRACE_MEDIA_READ, 53);
    return_value_if_fail(entry -> tx_trace_buffer_entry_time_stamp != first_timestamp, 54);

    /* The update is handed the first insert's timestamp, so it finds the id matching and
       the timestamp not, and declines the entry.  */
    _fx_trace_event_update(entry, first_timestamp, (ULONG) FX_TRACE_MEDIA_READ,
                           0, 0, 0, INFO_FIELD_1_VALUE);

    return_value_if_fail(entry -> tx_trace_buffer_entry_information_field_4 != INFO_FIELD_1_VALUE, 55);

    /* An update carrying the timestamp the entry actually has is accepted, which is what
       says the refusal above came from the timestamp and not from the call being rejected
       outright.  */
    timestamp =  entry -> tx_trace_buffer_entry_time_stamp;
    _fx_trace_event_update(entry, timestamp, (ULONG) FX_TRACE_MEDIA_READ,
                           0, 0, 0, INFO_FIELD_1_VALUE);

    return_value_if_fail(entry -> tx_trace_buffer_entry_information_field_4 == INFO_FIELD_1_VALUE, 56);

    tx_trace_disable();


    /* Close the media.  */
    status =  fx_media_close(&ram_disk);
    return_value_if_fail(status == FX_SUCCESS, 57);

    printf("SUCCESS!\n");
    test_control_return(0);
}

#else
#ifdef CTEST
void test_application_define(void *first_unused_memory)
#else
void    filex_trace_shim_coverage_test_application_define(void *first_unused_memory)
#endif
{

    FX_PARAMETER_NOT_USED(first_unused_memory);

    /* Print out some test information banners.  */
    printf("FileX Test:   Trace shim coverage test...............................N/A\n");

    test_control_return(255);
}
#endif
