/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 * 
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 * 
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 * 
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* This FileX test covers the arm that reports a corrupt fault-tolerant log to the caller
   of a repeated directory sector read.

   In a build with the sector cache disabled, the logical sector reader keeps the last
   single sector it read in the media's own memory buffer and short-circuits a repeat read
   of that same sector.  When fault tolerance is enabled and a transaction is open, the
   short-circuit is not the end of it: the directory sector still has to have the open
   transaction's uncommitted changes laid over it, so the reader calls the log reader even
   though it went nowhere near the driver.  The log reader rejects a log whose recorded
   entry length is longer than the log area that holds it, and the arm under test is the
   one that hands that refusal back to the caller.

   The reader has three call sites for the log reader and only one of them is this one.
   The other two -- the cached path, which this build does not compile, and the path taken
   after a fresh read from the driver -- are reached far more often, and a log left corrupt
   is always picked up by the fresh-read site first.  Measured rather than assumed: thirty
   injection points across five kinds of directory operation all produced FX_FILE_CORRUPT
   from the fresh-read site and none from this one, because a driver write is followed by a
   fresh read rather than by a repeat of the sector already held.

   So the corruption is placed and consumed inside one driver write callback, which is the
   only point at which a test runs with a real transaction open, real logs recorded, and a
   real directory sector sitting in the media memory buffer.  All three are conditions the
   running system produced; the callback fires once and checks each of them before it acts.

   What the callback does, and why each part of it is allowed:

   It alters the recorded length of the first log entry.  A corrupt log is a state the
   medium produces on its own -- an interrupted write or an unreadable sector leaves one
   behind, which is the failure the log reader's check exists for -- so this is fault
   injection into a state the file system meets in service rather than one manufactured for
   it.  Nothing else in the media is touched.

   It then re-reads the sector the media memory buffer is already holding, which is the
   read the arm under test belongs to.  _fx_utility_logical_sector_read is declared by
   common/inc/fx_utility.h, which this file includes, and the call supplies the media's own
   buffer and its own held sector number rather than anything built by hand.  The call is
   direct because the case cannot be placed any other way: the shipped callers reach this
   site constantly, but never with the log corrupt, since the fresh-read site catches a
   corrupt log first every time.  The short-circuit means no driver request is made, so the
   driver is not re-entered from its own callback.

   It then puts the log back.  The operation the callback interrupted therefore completes
   normally, and the test asserts that it did -- which is what says the injection was
   confined to the read under test and left the media consistent.

   Nothing is interposed.  No symbol is replaced and no FileX function is stubbed; the
   callback is a hook the suite's own RAM driver offers and seventy other tests already
   use, and every FileX function on the path runs its own code end to end.

   The constructs are compiled only where FX_DISABLE_CACHE and fault tolerance are both
   defined, so the test asserts in those two configurations and is reported N/A in the
   other nine.  */

#ifndef FX_STANDALONE_ENABLE
#include   "tx_api.h"
#endif
#include   "fx_api.h"
#include   "fx_utility.h"
#include   "fx_fault_tolerant.h"
#include   "fx_ram_driver_test.h"
#include   <stdio.h>

void  test_control_return(UINT status);
void  filex_fault_tolerant_no_cache_directory_log_error_test_application_define(void *first_unused_memory);

#if defined(FX_DISABLE_CACHE) && defined(FX_ENABLE_FAULT_TOLERANT) && defined(FX_FAULT_TOLERANT) && defined(FX_FAULT_TOLERANT_DATA)

#define     DEMO_STACK_SIZE         4096
#define     CACHE_SIZE              2048
#define     SECTOR_SIZE             256
#define     SECTORS_PER_CLUSTER     8
#define     TOTAL_SECTORS           256
#define     FAULT_TOLERANT_SIZE     FX_FAULT_TOLERANT_MINIMAL_BUFFER_SIZE

#define     FILE_SIZE               (SECTOR_SIZE * 4)

/* A recorded entry length larger than any log area this media can have, which is what the
   log reader's size check rejects.  */
#define     CORRUPT_LOG_LENGTH      0xFFFF

/* The offset of the first log entry's length field within the log area.  */
#define     FIRST_LOG_ENTRY_OFFSET  (FX_FAULT_TOLERANT_LOG_CONTENT_OFFSET +               \
                                     FX_FAULT_TOLERANT_LOG_CONTENT_HEADER_SIZE)
#define     LOG_ENTRY_LENGTH_OFFSET 2


/* Define the ThreadX and FileX object control blocks...  */

#ifndef FX_STANDALONE_ENABLE
static TX_THREAD               ftest_0;
#endif
static FX_MEDIA                ram_disk;
static FX_FILE                 my_file;


/* Define the counters used in the test application...  */

#ifndef FX_STANDALONE_ENABLE
static UCHAR                  *cache_buffer;
static UCHAR                  *fault_tolerant_buffer;
#else
static UCHAR                   cache_buffer[CACHE_SIZE];
static UCHAR                   fault_tolerant_buffer[FAULT_TOLERANT_SIZE];
#endif

static UCHAR                   data_buffer[FILE_SIZE];

/* What the callback did, so the thread can assert on it rather than on the operation's
   status alone.  */
static UINT                    injection_armed;
static UINT                    injection_count;
static UINT                    injected_read_status;
static ULONG64                 injected_sector;


/* Define thread prototypes.  */

static void    ftest_0_entry(ULONG thread_input);

VOID  _fx_ram_driver(FX_MEDIA *media_ptr);

extern UINT (*driver_write_callback)(FX_MEDIA *media_ptr, UINT sector_type, UCHAR *block_ptr, UINT *operation_ptr);


/* Define what the initial system looks like.  */

#ifdef CTEST
void test_application_define(void *first_unused_memory)
#else
void    filex_fault_tolerant_no_cache_directory_log_error_test_application_define(void *first_unused_memory)
#endif
{

#ifndef FX_STANDALONE_ENABLE
UCHAR    *pointer;


    /* Setup the working pointer.  */
    pointer =  (UCHAR *) first_unused_memory;

    /* Create the main thread.  */
    tx_thread_create(&ftest_0, "thread 0", ftest_0_entry, 0,  
            pointer, DEMO_STACK_SIZE, 
            4, 4, TX_NO_TIME_SLICE, TX_AUTO_START);

    pointer =  pointer + DEMO_STACK_SIZE;

    /* Setup memory for the sector cache and the fault-tolerant log.  */
    cache_buffer =  pointer;
    pointer =  pointer + CACHE_SIZE;
    fault_tolerant_buffer =  pointer;

#else
    FX_PARAMETER_NOT_USED(first_unused_memory);
#endif

    /* Initialize the FileX system.  */
    fx_system_initialize();
#ifdef FX_STANDALONE_ENABLE
    ftest_0_entry(0);
#endif
}


/* Corrupt the log, re-read the directory sector the media memory buffer is already
   holding, and put the log back.  Fires once, and only with a transaction open, a log
   recorded and a sector held -- all three of which the running operation produced.  */

static UINT  corrupt_log_write_callback(FX_MEDIA *media_ptr, UINT sector_type,
                                        UCHAR *block_ptr, UINT *operation_ptr)
{

UCHAR   *log_entry_ptr;
UINT     saved_length;


    FX_PARAMETER_NOT_USED(sector_type);
    FX_PARAMETER_NOT_USED(block_ptr);

    /* The write itself is left alone.  */
    *operation_ptr =  FX_OP_WRITE_NORMALLY;

    if ((injection_armed) &&
        (media_ptr -> fx_media_fault_tolerant_total_logs > 0) &&
        (media_ptr -> fx_media_fault_tolerant_state & FX_FAULT_TOLERANT_STATE_STARTED) &&
        (media_ptr -> fx_media_memory_buffer_sector != (ULONG64) -1))
    {

        injection_armed =  FX_FALSE;
        injection_count++;
        injected_sector =  media_ptr -> fx_media_memory_buffer_sector;

        log_entry_ptr =  media_ptr -> fx_media_fault_tolerant_memory_buffer + FIRST_LOG_ENTRY_OFFSET;
        saved_length =  _fx_utility_16_unsigned_read(log_entry_ptr + LOG_ENTRY_LENGTH_OFFSET);

        /* Claim a length the log area cannot hold.  */
        _fx_utility_16_unsigned_write(log_entry_ptr + LOG_ENTRY_LENGTH_OFFSET, CORRUPT_LOG_LENGTH);

        /* Read back the sector the memory buffer is already holding.  The reader
           short-circuits the medium and goes straight to the log, which is now corrupt.  */
        injected_read_status =  _fx_utility_logical_sector_read(media_ptr,
                                                               media_ptr -> fx_media_memory_buffer_sector,
                                                               media_ptr -> fx_media_memory_buffer,
                                                               1, FX_DIRECTORY_SECTOR);

        /* Put the log back, so the operation this interrupted can finish.  */
        _fx_utility_16_unsigned_write(log_entry_ptr + LOG_ENTRY_LENGTH_OFFSET, saved_length);
    }

    return(FX_SUCCESS);
}


/* Define the test threads.  */

static void    ftest_0_entry(ULONG thread_input)
{

UINT        status;
ULONG       actual;
ULONG       i;


    FX_PARAMETER_NOT_USED(thread_input);

    /* Print out some test information banners.  */
    printf("FileX Test:   Fault tolerant no cache directory log error test.......");

    /* Format the media.  This needs to be done before opening it!  */
    status =  fx_media_format(&ram_disk, 
                            _fx_ram_driver,         // Driver entry
                            ram_disk_memory_large,  // RAM disk memory pointer
                            cache_buffer,           // Media buffer pointer
                            CACHE_SIZE,             // Media buffer size 
                            "MY_RAM_DISK",          // Volume Name
                            1,                      // Number of FATs
                            32,                     // Directory Entries
                            0,                      // Hidden sectors
                            TOTAL_SECTORS,          // Total sectors 
                            SECTOR_SIZE,            // Sector size   
                            SECTORS_PER_CLUSTER,    // Sectors per cluster
                            1,                      // Heads
                            1);                     // Sectors per track 
    return_value_if_fail(status == FX_SUCCESS, 1);

    /* Open the RAM disk.  */
    status =  fx_media_open(&ram_disk, "RAM DISK", _fx_ram_driver, ram_disk_memory_large, cache_buffer, CACHE_SIZE);
    return_value_if_fail(status == FX_SUCCESS, 2);

    status =  fx_fault_tolerant_enable(&ram_disk, fault_tolerant_buffer, FAULT_TOLERANT_SIZE);
    return_value_if_fail(status == FX_SUCCESS, 3);

    for (i = 0; i < FILE_SIZE; i++)
    {
        data_buffer[i] =  (UCHAR) i;
    }

    /* The callback is left armed across a sequence of directory and file work rather than
       over one call, because the three conditions it waits for do not all hold at the
       first write of an operation on a freshly enabled media: a transaction has to be open
       at the moment a write goes out, a log has to have been recorded by then, and a
       directory sector has to be sitting in the memory buffer.  Measured on this media,
       the writes of a directory create carry no logs yet, and those of the file create
       that follows it land after their transaction has closed.  The callback checks all
       three itself and fires once, at the first write where they hold together; which of
       these calls hosts it is not what the test is about, and the assertions below do not
       depend on it.  */

    injection_armed =         FX_TRUE;
    injection_count =         0;
    injected_read_status =    FX_SUCCESS;
    driver_write_callback =   corrupt_log_write_callback;

    status =  fx_directory_create(&ram_disk, "SUB");
    return_value_if_fail(status == FX_SUCCESS, 4);

    status =  fx_file_create(&ram_disk, "SUB/FIRST.TXT");
    return_value_if_fail(status == FX_SUCCESS, 5);

    status =  fx_file_open(&ram_disk, &my_file, "SUB/FIRST.TXT", FX_OPEN_FOR_WRITE);
    return_value_if_fail(status == FX_SUCCESS, 6);

    status =  fx_file_write(&my_file, data_buffer, FILE_SIZE);
    return_value_if_fail(status == FX_SUCCESS, 7);

    status =  fx_file_close(&my_file);
    return_value_if_fail(status == FX_SUCCESS, 8);

    status =  fx_file_delete(&ram_disk, "SUB/FIRST.TXT");
    return_value_if_fail(status == FX_SUCCESS, 9);

    driver_write_callback =   FX_NULL;
    injection_armed =         FX_FALSE;

    /* The injection happened, once.  */
    return_value_if_fail(injection_count == 1, 10);

    /* It was placed on a real sector rather than on an unset buffer.  */
    return_value_if_fail(injected_sector != (ULONG64) -1, 11);

    /* And the repeated read of that sector reported the log corrupt, which is the arm
       this test exists for.  */
    return_value_if_fail(injected_read_status == FX_FILE_CORRUPT, 12);


    /* The media is intact: the same read now succeeds, a file written into the new
       directory reads back byte for byte, and the media closes cleanly.  */

    status =  _fx_utility_logical_sector_read(&ram_disk, injected_sector,
                                              ram_disk.fx_media_memory_buffer,
                                              1, FX_DIRECTORY_SECTOR);
    return_value_if_fail(status == FX_SUCCESS, 13);

    status =  fx_file_create(&ram_disk, "SUB/AFTER.TXT");
    return_value_if_fail(status == FX_SUCCESS, 14);

    status =  fx_file_open(&ram_disk, &my_file, "SUB/AFTER.TXT", FX_OPEN_FOR_WRITE);
    return_value_if_fail(status == FX_SUCCESS, 15);

    status =  fx_file_write(&my_file, data_buffer, FILE_SIZE);
    return_value_if_fail(status == FX_SUCCESS, 16);

    status =  fx_file_close(&my_file);
    return_value_if_fail(status == FX_SUCCESS, 17);

    memset(data_buffer, 0, FILE_SIZE);

    status =  fx_file_open(&ram_disk, &my_file, "SUB/AFTER.TXT", FX_OPEN_FOR_READ);
    return_value_if_fail(status == FX_SUCCESS, 18);

    status =  fx_file_read(&my_file, data_buffer, FILE_SIZE, &actual);
    return_value_if_fail(status == FX_SUCCESS, 19);
    return_value_if_fail(actual == FILE_SIZE, 20);

    for (i = 0; i < FILE_SIZE; i++)
    {
        return_value_if_fail(data_buffer[i] == (UCHAR) i, 21);
    }

    status =  fx_file_close(&my_file);
    return_value_if_fail(status == FX_SUCCESS, 22);

    /* Close the media.  */
    status =  fx_media_close(&ram_disk);
    return_value_if_fail(status == FX_SUCCESS, 23);

    printf("SUCCESS!\n");
    test_control_return(0);
}

#else
#ifdef CTEST
void test_application_define(void *first_unused_memory)
#else
void    filex_fault_tolerant_no_cache_directory_log_error_test_application_define(void *first_unused_memory)
#endif
{

    FX_PARAMETER_NOT_USED(first_unused_memory);

    /* Print out some test information banners.  */
    printf("FileX Test:   Fault tolerant no cache directory log error test.......N/A\n");

    test_control_return(255);
}
#endif
