/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 * 
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 * 
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 * 
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* This FileX test concentrates on the selective I/O error injection in the regression
   suite's RAM driver -- failing a nominated driver request at a nominated sector -- and
   drives it through the public fx_media_read and fx_media_write services.

   No symbol is replaced and no FileX function is stubbed.  A media driver is an
   application-supplied function pointer handed to fx_media_open, so a driver that reports
   FX_IO_ERROR for one sector is an ordinary application driver reporting an ordinary
   medium failure rather than an interposition -- which is also why the coverage report
   excludes the driver sources.  Nothing here manufactures a state the file system could
   not meet in service: an unreadable or unwritable sector is the failure every block
   medium has.

   The test asserts in all eleven build configurations and has no N/A arm.  The services it
   drives, the driver contract and the selector are compiled by every one of them.  */

#ifndef FX_STANDALONE_ENABLE
#include   "tx_api.h"
#endif
#include   "fx_api.h"
#include   "fx_ram_driver_test.h"
#include   <stdio.h>

void  test_control_return(UINT status);

#define     DEMO_STACK_SIZE         4096
#define     CACHE_SIZE              128*128
#define     SECTOR_SIZE             128
#define     TOTAL_SECTORS           256

/* The sectors the test injects at.  Each is used once, and none of them is touched by the
   format or the open, so a request for one always reaches the driver rather than being
   served from the sector cache.  */

#define     SECTOR_READ_FAIL        100
#define     SECTOR_WRITE_FAIL       101
#define     SECTOR_REQUEST_SELECT   102
#define     SECTOR_UNSELECTED       103
#define     SECTOR_SELECTED         104
#define     SECTOR_DISARMED         105
#define     SECTOR_COUNTDOWN        106


/* Define the ThreadX and FileX object control blocks...  */

#ifndef FX_STANDALONE_ENABLE
static TX_THREAD               ftest_0;
#endif
static FX_MEDIA                ram_disk;

static UCHAR                   raw_sector_buffer[SECTOR_SIZE];


/* Define the counters used in the test application...  */

#ifndef FX_STANDALONE_ENABLE
static UCHAR                  *ram_disk_memory;
static UCHAR                  *cache_buffer;
#else
static UCHAR                   cache_buffer[CACHE_SIZE];
#endif


/* Define thread prototypes.  */

void    filex_media_driver_io_error_application_define(void *first_unused_memory);
static void    ftest_0_entry(ULONG thread_input);

VOID  _fx_ram_driver(FX_MEDIA *media_ptr);


/* Define what the initial system looks like.  */

#ifdef CTEST
void test_application_define(void *first_unused_memory)
#else
void    filex_media_driver_io_error_application_define(void *first_unused_memory)
#endif
{

#ifndef FX_STANDALONE_ENABLE
UCHAR    *pointer;


    /* Setup the working pointer.  */
    pointer =  (UCHAR *) first_unused_memory;

    /* Create the main thread.  */
    tx_thread_create(&ftest_0, "thread 0", ftest_0_entry, 0,  
            pointer, DEMO_STACK_SIZE, 
            4, 4, TX_NO_TIME_SLICE, TX_AUTO_START);

    pointer =  pointer + DEMO_STACK_SIZE;

    /* Setup memory for the RAM disk and the sector cache.  */
    cache_buffer =  pointer;
    pointer =  pointer + CACHE_SIZE;
    ram_disk_memory =  pointer;

#else
    FX_PARAMETER_NOT_USED(first_unused_memory);
#endif

    /* Initialize the FileX system.  */
    fx_system_initialize();
#ifdef FX_STANDALONE_ENABLE
    ftest_0_entry(0);
#endif
}


/* Arm the selector for one request of the given kind at the given sector.  */

static void    arm_selector(ULONG request, ULONG64 sector)
{

    _fx_ram_driver_io_error_select_request =  request;
    _fx_ram_driver_io_error_select_sector =   sector;
    _fx_ram_driver_io_error_select =          FX_TRUE;
}


/* Define the test threads.  */

static void    ftest_0_entry(ULONG thread_input)
{

UINT        status;

    FX_PARAMETER_NOT_USED(thread_input);

    /* Print out some test information banners.  */
    printf("FileX Test:   Media driver I/O error test............................");

    /* Format the media.  This needs to be done before opening it!  */
    status =  fx_media_format(&ram_disk, 
                            _fx_ram_driver,         // Driver entry
                            ram_disk_memory,        // RAM disk memory pointer
                            cache_buffer,           // Media buffer pointer
                            CACHE_SIZE,             // Media buffer size 
                            "MY_RAM_DISK",          // Volume Name
                            1,                      // Number of FATs
                            32,                     // Directory Entries
                            0,                      // Hidden sectors
                            TOTAL_SECTORS,          // Total sectors 
                            SECTOR_SIZE,            // Sector size   
                            1,                      // Sectors per cluster
                            1,                      // Heads
                            1);                     // Sectors per track 
    return_value_if_fail(status == FX_SUCCESS, 1);

    /* Open the RAM disk.  */
    status =  fx_media_open(&ram_disk, "RAM DISK", _fx_ram_driver, ram_disk_memory, cache_buffer, CACHE_SIZE);
    return_value_if_fail(status == FX_SUCCESS, 2);

    /* The selector starts disarmed and has failed nothing.  */
    return_value_if_fail(_fx_ram_driver_io_error_select == FX_FALSE, 3);
    _fx_ram_driver_io_error_select_count =  0;

    /* A read that the driver fails is reported to the caller of fx_media_read.  */
    arm_selector(FX_DRIVER_READ, SECTOR_READ_FAIL);
    status =  fx_media_read(&ram_disk, SECTOR_READ_FAIL, (VOID *) raw_sector_buffer);
    return_value_if_fail(status == FX_IO_ERROR, 4);
    return_value_if_fail(_fx_ram_driver_io_error_select_count == 1, 5);

    /* Firing disarms the selector, so the media is usable again.  */
    return_value_if_fail(_fx_ram_driver_io_error_select == FX_FALSE, 6);

    /* A write that the driver fails is reported to the caller of fx_media_write.  */
    arm_selector(FX_DRIVER_WRITE, SECTOR_WRITE_FAIL);
    status =  fx_media_write(&ram_disk, SECTOR_WRITE_FAIL, (VOID *) raw_sector_buffer);
    return_value_if_fail(status == FX_IO_ERROR, 7);
    return_value_if_fail(_fx_ram_driver_io_error_select_count == 2, 8);

    /* The selector picks the request kind.  Armed for a read, it lets a write at the same
       sector through.  */
    arm_selector(FX_DRIVER_READ, SECTOR_REQUEST_SELECT);
    status =  fx_media_write(&ram_disk, SECTOR_REQUEST_SELECT, (VOID *) raw_sector_buffer);
    return_value_if_fail(status == FX_SUCCESS, 9);
    return_value_if_fail(_fx_ram_driver_io_error_select_count == 2, 10);

    /* It is still armed, and the read it was armed for fails.  */
    status =  fx_media_read(&ram_disk, SECTOR_REQUEST_SELECT, (VOID *) raw_sector_buffer);
    return_value_if_fail(status == FX_IO_ERROR, 11);
    return_value_if_fail(_fx_ram_driver_io_error_select_count == 3, 12);

    /* The selector picks the sector.  Armed for one sector, it lets the same request at a
       different sector through.  */
    arm_selector(FX_DRIVER_READ, SECTOR_SELECTED);
    status =  fx_media_read(&ram_disk, SECTOR_UNSELECTED, (VOID *) raw_sector_buffer);
    return_value_if_fail(status == FX_SUCCESS, 13);
    return_value_if_fail(_fx_ram_driver_io_error_select_count == 3, 14);

    status =  fx_media_read(&ram_disk, SECTOR_SELECTED, (VOID *) raw_sector_buffer);
    return_value_if_fail(status == FX_IO_ERROR, 15);
    return_value_if_fail(_fx_ram_driver_io_error_select_count == 4, 16);

    /* Disarmed, the driver is the driver every other test sees.  */
    status =  fx_media_read(&ram_disk, SECTOR_DISARMED, (VOID *) raw_sector_buffer);
    return_value_if_fail(status == FX_SUCCESS, 17);
    status =  fx_media_write(&ram_disk, SECTOR_DISARMED, (VOID *) raw_sector_buffer);
    return_value_if_fail(status == FX_SUCCESS, 18);
    return_value_if_fail(_fx_ram_driver_io_error_select_count == 4, 19);

    /* The Nth-request countdown the rest of the suite uses is unaffected by the selector
       and still fails the next request of any kind.  */
    _fx_ram_driver_io_error_request =  1;
    status =  fx_media_read(&ram_disk, SECTOR_COUNTDOWN, (VOID *) raw_sector_buffer);
    _fx_ram_driver_io_error_request =  0;
    return_value_if_fail(status == FX_IO_ERROR, 20);
    return_value_if_fail(_fx_ram_driver_io_error_select_count == 4, 21);

    /* Close the media.  */
    status =  fx_media_close(&ram_disk);
    return_value_if_fail(status == FX_SUCCESS, 22);

    printf("SUCCESS!\n");
    test_control_return(0);
}
