/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 * 
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 * 
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 * 
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* This FileX test concentrates on the error arm of the FAT entry read that _fx_file_write
   issues for the cluster following the copy tail.  That read is on the fault-tolerant
   insert path, taken when a write lands in the middle of an existing file rather than at
   its end: the clusters it overwrites have to be replaced rather than appended, and this
   read is what finds where the replacement chain rejoins the file.  The read succeeds
   everywhere else in the suite, so the arm that reports it failing to the caller of
   fx_file_write is what this test exists for.

   The failure is injected through FX_UTILITY_FAT_ENTRY_READ_EXTENSION, the Linux port's
   FAT-entry test hook, which every build of this suite defines and which ten other tests
   here already use.  Armed with 1, it makes the next _fx_utility_FAT_entry_read return
   FX_IO_ERROR and disarms itself.

   Two things are asserted rather than assumed, because the returned status alone would
   establish neither.  A clean write of the same shape issues three FAT entry reads, so
   failing the first is a placed injection and not the only one on offer.  And the failing
   write is asserted to have issued exactly one, which is what says the error came from
   that first read rather than from anything later in the call.

   Nothing is interposed.  No symbol is replaced and no FileX function is stubbed: the hook
   is code the port contributes to _fx_utility_FAT_entry_read itself, and every other FileX
   function on the path runs its own code end to end.  Nor is any state manufactured that
   the file system could not meet in service.  FX_IO_ERROR is what _fx_utility_FAT_entry_read
   returns on its own when the sector read behind it fails, and an unreadable FAT sector is
   the failure every block medium has.  The rest of the system under this test is the
   certified system, and the test closes by reading the file back to show that the
   transaction the injection aborted left the media and the file intact.

   A driver-level injection was measured first and does not reach this read.  All three of
   the FAT entry reads the write issues are served from the FAT entry cache, in every
   configuration -- FX_DISABLE_CACHE does not disable that cache -- so the driver is asked
   for none of them and a driver told to fail one nominated sector never fires.  The port
   hook sits above the cache and behaves identically in all five fault-tolerant
   configurations.

   The test asserts in those five and is reported N/A in the other six.  */

#ifndef FX_STANDALONE_ENABLE
#include   "tx_api.h"
#endif
#include   "fx_api.h"
#include   "fx_fault_tolerant.h"
#include   "fx_ram_driver_test.h"
#include   <stdio.h>

void  test_control_return(UINT status);
void  filex_fault_tolerant_file_write_fat_read_error_test_application_define(void *first_unused_memory);

#if defined (FX_ENABLE_FAULT_TOLERANT) && defined (FX_FAULT_TOLERANT) && defined (FX_FAULT_TOLERANT_DATA)

#define     DEMO_STACK_SIZE         4096
#define     CACHE_SIZE              2048
#define     FAULT_TOLERANT_SIZE     FX_FAULT_TOLERANT_MINIMAL_BUFFER_SIZE

/* The media is deliberately small.  Two clusters of file and an insert of two sectors are
   all the insert path needs, and the insert has to span a sector boundary or the write is
   taken as an overwrite within one sector and replaces no clusters at all.  */

#define     SECTOR_SIZE             256
#define     SECTORS_PER_CLUSTER     8
#define     TOTAL_SECTORS           256
#define     BYTES_PER_CLUSTER       (SECTOR_SIZE * SECTORS_PER_CLUSTER)
#define     FILE_SIZE               (BYTES_PER_CLUSTER * 2)
#define     INSERT_SIZE             (SECTOR_SIZE * 2)

#define     FILE_FILL               0x5A
#define     INSERT_FILL             0xA5

/* The number of FAT entry reads a clean write of this shape issues.  The injection takes
   the first of them, which is the read under test.  */

#define     CLEAN_WRITE_FAT_READS   3


/* Define the ThreadX and FileX object control blocks...  */

#ifndef FX_STANDALONE_ENABLE
static TX_THREAD               ftest_0;
#endif
static FX_MEDIA                ram_disk;
static FX_FILE                 my_file;


/* Define the counters used in the test application...  */

#ifndef FX_STANDALONE_ENABLE
static UCHAR                  *cache_buffer;
static UCHAR                  *fault_tolerant_buffer;
#else
static UCHAR                   cache_buffer[CACHE_SIZE];
static UCHAR                   fault_tolerant_buffer[FAULT_TOLERANT_SIZE];
#endif

static UCHAR                   data_buffer[FILE_SIZE];


/* Define thread prototypes.  */

static void    ftest_0_entry(ULONG thread_input);

VOID  _fx_ram_driver(FX_MEDIA *media_ptr);


/* Define what the initial system looks like.  */

#ifdef CTEST
void test_application_define(void *first_unused_memory)
#else
void    filex_fault_tolerant_file_write_fat_read_error_test_application_define(void *first_unused_memory)
#endif
{

#ifndef FX_STANDALONE_ENABLE
UCHAR    *pointer;


    /* Setup the working pointer.  */
    pointer =  (UCHAR *) first_unused_memory;

    /* Create the main thread.  */
    tx_thread_create(&ftest_0, "thread 0", ftest_0_entry, 0,  
            pointer, DEMO_STACK_SIZE, 
            4, 4, TX_NO_TIME_SLICE, TX_AUTO_START);

    pointer =  pointer + DEMO_STACK_SIZE;

    /* Setup memory for the sector cache and the fault-tolerant log.  */
    cache_buffer =  pointer;
    pointer =  pointer + CACHE_SIZE;
    fault_tolerant_buffer =  pointer;

#else
    FX_PARAMETER_NOT_USED(first_unused_memory);
#endif

    /* Initialize the FileX system.  */
    fx_system_initialize();
#ifdef FX_STANDALONE_ENABLE
    ftest_0_entry(0);
#endif
}


/* Format a media, enable fault tolerance on it, and leave a two-cluster file open for
   writing and positioned at its start.  A write issued from there lands in the middle of
   the file, which is what takes _fx_file_write down the insert path.  */

static UINT    build_media_and_file(void)
{

UINT        status;
UINT        i;


    status =  fx_media_format(&ram_disk, 
                            _fx_ram_driver,         // Driver entry
                            ram_disk_memory_large,  // RAM disk memory pointer
                            cache_buffer,           // Media buffer pointer
                            CACHE_SIZE,             // Media buffer size 
                            "MY_RAM_DISK",          // Volume Name
                            1,                      // Number of FATs
                            32,                     // Directory Entries
                            0,                      // Hidden sectors
                            TOTAL_SECTORS,          // Total sectors 
                            SECTOR_SIZE,            // Sector size   
                            SECTORS_PER_CLUSTER,    // Sectors per cluster
                            1,                      // Heads
                            1);                     // Sectors per track 
    if (status != FX_SUCCESS)
    {
        return(status);
    }

    status =  fx_media_open(&ram_disk, "RAM DISK", _fx_ram_driver, ram_disk_memory_large, cache_buffer, CACHE_SIZE);
    if (status != FX_SUCCESS)
    {
        return(status);
    }

    status =  fx_fault_tolerant_enable(&ram_disk, fault_tolerant_buffer, FAULT_TOLERANT_SIZE);
    if (status != FX_SUCCESS)
    {
        return(status);
    }

    status =  fx_file_create(&ram_disk, "TEST.TXT");
    if (status != FX_SUCCESS)
    {
        return(status);
    }

    status =  fx_file_open(&ram_disk, &my_file, "TEST.TXT", FX_OPEN_FOR_WRITE);
    if (status != FX_SUCCESS)
    {
        return(status);
    }

    for (i = 0; i < FILE_SIZE; i++)
    {
        data_buffer[i] =  (UCHAR) FILE_FILL;
    }

    status =  fx_file_write(&my_file, data_buffer, FILE_SIZE);
    if (status != FX_SUCCESS)
    {
        return(status);
    }

    status =  fx_file_close(&my_file);
    if (status != FX_SUCCESS)
    {
        return(status);
    }

    /* Reopen and rewind, so the next write overwrites rather than appends.  */
    status =  fx_file_open(&ram_disk, &my_file, "TEST.TXT", FX_OPEN_FOR_WRITE);
    if (status != FX_SUCCESS)
    {
        return(status);
    }

    return(fx_file_seek(&my_file, 0));
}


/* Define the test threads.  */

static void    ftest_0_entry(ULONG thread_input)
{

UINT        status;
UINT        i;
ULONG       actual;
ULONG       fat_reads;

    FX_PARAMETER_NOT_USED(thread_input);

    /* Print out some test information banners.  */
    printf("FileX Test:   Fault Tolerant File Write FAT Read Error Test.........");

    /* The same write, uninjected, establishes what the insert path does when nothing fails
       and how many FAT entry reads it takes to do it.  */

    status =  build_media_and_file();
    return_value_if_fail(status == FX_SUCCESS, 1);

    /* The write about to be issued lands in the middle of the file rather than at its end,
       which is the condition the insert path is selected on.  */
    return_value_if_fail(my_file.fx_file_current_file_offset == 0, 2);
    return_value_if_fail(my_file.fx_file_current_file_size == FILE_SIZE, 3);
    return_value_if_fail(my_file.fx_file_current_physical_cluster == my_file.fx_file_first_physical_cluster, 4);

    for (i = 0; i < INSERT_SIZE; i++)
    {
        data_buffer[i] =  (UCHAR) INSERT_FILL;
    }

    fat_reads =  _fx_utility_fat_entry_read_count;
    status =  fx_file_write(&my_file, data_buffer, INSERT_SIZE);
    return_value_if_fail(status == FX_SUCCESS, 5);
    return_value_if_fail((_fx_utility_fat_entry_read_count - fat_reads) == CLEAN_WRITE_FAT_READS, 6);

    status =  fx_file_close(&my_file);
    return_value_if_fail(status == FX_SUCCESS, 7);
    status =  fx_media_close(&ram_disk);
    return_value_if_fail(status == FX_SUCCESS, 8);

    /* The same write again, with the first of those three FAT entry reads failing.  */

    status =  build_media_and_file();
    return_value_if_fail(status == FX_SUCCESS, 9);

    for (i = 0; i < INSERT_SIZE; i++)
    {
        data_buffer[i] =  (UCHAR) INSERT_FILL;
    }

    fat_reads =  _fx_utility_fat_entry_read_count;
    _fx_utility_fat_entry_read_error_request =  1;
    status =  fx_file_write(&my_file, data_buffer, INSERT_SIZE);

    /* The error the FAT read reported reaches the caller of fx_file_write.  */
    return_value_if_fail(status == FX_IO_ERROR, 10);

    /* It reached it from the first FAT entry read of the call rather than from a later
       one: this write issued exactly one where the clean write issued three.  */
    return_value_if_fail((_fx_utility_fat_entry_read_count - fat_reads) == 1, 11);

    /* The hook disarmed itself as it fired, so nothing after this point is injected.  */
    return_value_if_fail(_fx_utility_fat_entry_read_error_request == 0, 12);

    /* The transaction the failure aborted left the file as it was.  */
    status =  fx_file_close(&my_file);
    return_value_if_fail(status == FX_SUCCESS, 13);

    status =  fx_file_open(&ram_disk, &my_file, "TEST.TXT", FX_OPEN_FOR_READ);
    return_value_if_fail(status == FX_SUCCESS, 14);
    return_value_if_fail(my_file.fx_file_current_file_size == FILE_SIZE, 15);

    for (i = 0; i < FILE_SIZE; i++)
    {
        data_buffer[i] =  0;
    }

    status =  fx_file_read(&my_file, data_buffer, FILE_SIZE, &actual);
    return_value_if_fail(status == FX_SUCCESS, 16);
    return_value_if_fail(actual == FILE_SIZE, 17);

    for (i = 0; i < FILE_SIZE; i++)
    {
        return_value_if_fail(data_buffer[i] == (UCHAR) FILE_FILL, 18);
    }

    status =  fx_file_close(&my_file);
    return_value_if_fail(status == FX_SUCCESS, 19);
    status =  fx_media_close(&ram_disk);
    return_value_if_fail(status == FX_SUCCESS, 20);

    printf("SUCCESS!\n");
    test_control_return(0);
}

#else

#ifdef CTEST
void test_application_define(void *first_unused_memory)
#else
void    filex_fault_tolerant_file_write_fat_read_error_test_application_define(void *first_unused_memory)
#endif
{

    FX_PARAMETER_NOT_USED(first_unused_memory);

    /* Print out some test information banners.  */
    printf("FileX Test:   Fault Tolerant File Write FAT Read Error Test.........N/A\n");

    test_control_return(255);
}
#endif
