/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 *
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 *
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* This FileX test concentrates on the bounds applied to fault-tolerant log replay.

   A directory log entry names the offset and the size of a copy into a single
   sector staged at fx_media_memory_buffer.  Both values come off the media, so
   the replay path has to bound them against the sector size rather than against
   the whole cache allocation, and a re-mounted clean log has to keep working.  */

#ifndef FX_STANDALONE_ENABLE
#include   "tx_api.h"
#include   "tx_thread.h"
#include   "tx_timer.h"
#endif
#include   "fx_api.h"
#include   "fx_utility.h"
#include   "fx_fault_tolerant.h"
#include   <stdio.h>
#include   "fx_ram_driver_test.h"
extern void    test_control_return(UINT status);
void    filex_fault_tolerant_apply_logs_bounds_test_application_define(void *first_unused_memory);

#if defined (FX_ENABLE_FAULT_TOLERANT) && defined (FX_FAULT_TOLERANT)

#define DEMO_STACK_SIZE         4096
#define CACHE_SIZE              2048
#define FAULT_TOLERANT_SIZE     FX_FAULT_TOLERANT_MINIMAL_BUFFER_SIZE
#define FAULT_TOLERANT_BUFFER   (FX_FAULT_TOLERANT_MAXIMUM_LOG_FILE_SIZE + 1024)
#define BYTES_PER_SECTOR        256


/* Define the ThreadX and FileX object control blocks...  */

#ifndef FX_STANDALONE_ENABLE
static TX_THREAD                ftest_0;
static UCHAR                    *cache_buffer;
static UCHAR                    *fault_tolerant_buffer;
#else
static UCHAR                    cache_buffer[CACHE_SIZE];
static UCHAR                    fault_tolerant_buffer[FAULT_TOLERANT_BUFFER];
#endif
static FX_MEDIA                 ram_disk;
static UCHAR                    *pointer;

/* Define thread prototypes.  */

static void    ftest_0_entry(ULONG thread_input);
extern void    _fx_ram_driver(FX_MEDIA *media_ptr);
extern void    test_control_return(UINT status);


/* Format and open the media, then enable fault tolerance.  */
static UINT    media_prepare(VOID)
{

UINT        status;

    status =  fx_media_format(&ram_disk,
                              _fx_ram_driver,         // Driver entry
                              ram_disk_memory_large,  // RAM disk memory pointer
                              cache_buffer,           // Media buffer pointer
                              CACHE_SIZE,             // Media buffer size
                              "MY_RAM_DISK",          // Volume Name
                              1,                      // Number of FATs
                              32,                     // Directory Entries
                              0,                      // Hidden sectors
                              256,                    // Total sectors
                              BYTES_PER_SECTOR,       // Sector size
                              8,                      // Sectors per cluster
                              1,                      // Heads
                              1);                     // Sectors per track
    if (status != FX_SUCCESS)
    {
        return(status);
    }

    status =  fx_media_open(&ram_disk, "RAM DISK", _fx_ram_driver, ram_disk_memory_large,
                            cache_buffer, CACHE_SIZE);
    if (status != FX_SUCCESS)
    {
        return(status);
    }

    return(fx_fault_tolerant_enable(&ram_disk, fault_tolerant_buffer, FAULT_TOLERANT_SIZE));
}


/* Return a logical sector inside the fault-tolerant log file, past its header.  */
static ULONG64 log_data_sector(VOID)
{

    return(((ULONG64)ram_disk.fx_media_data_sector_start) +
           (((ULONG64)(ram_disk.fx_media_fault_tolerant_start_cluster + 1 - FX_FAT_ENTRY_START)) *
            ((ULONG64)ram_disk.fx_media_sectors_per_cluster)));
}


/* Return the logical sector holding the fault-tolerant log file's header.  */
static ULONG64 log_header_sector(VOID)
{

    return(((ULONG64)ram_disk.fx_media_data_sector_start) +
           (((ULONG64)(ram_disk.fx_media_fault_tolerant_start_cluster - FX_FAT_ENTRY_START)) *
            ((ULONG64)ram_disk.fx_media_sectors_per_cluster)));
}


/* Stage one directory log entry and force its copy offset, then replay the log.  */
static UINT    replay_dir_log_at_offset(ULONG offset)
{

UINT                       status;
UINT                       payload = 0;
FX_FAULT_TOLERANT_DIR_LOG *dir_log;

    status =  media_prepare();
    if (status != FX_SUCCESS)
    {
        return(status);
    }

    _fx_fault_tolerant_transaction_start(&ram_disk);

    /* The next log entry lands at the current end of the log file.  */
    dir_log =  (FX_FAULT_TOLERANT_DIR_LOG *)(ram_disk.fx_media_fault_tolerant_memory_buffer +
                                             ram_disk.fx_media_fault_tolerant_file_size);

    status =  _fx_fault_tolerant_add_dir_log(&ram_disk, log_data_sector(), 1, (UCHAR *)&payload, 1);
    if (status != FX_SUCCESS)
    {
        return(status);
    }

    /* Point the copy past the end of the destination sector.  */
    _fx_utility_32_unsigned_write((UCHAR *)&dir_log -> fx_fault_tolerant_dir_log_offset, offset);

    return(_fx_fault_tolerant_transaction_end(&ram_disk));
}


/* Stage one directory log entry, then shrink the recorded log size so the entry
   claims more than the log file holds, and replay the log.  */
static UINT    replay_dir_log_short_by(ULONG shortfall)
{

UINT        status;
UINT        payload = 0;

    status =  media_prepare();
    if (status != FX_SUCCESS)
    {
        return(status);
    }

    _fx_fault_tolerant_transaction_start(&ram_disk);

    status =  _fx_fault_tolerant_add_dir_log(&ram_disk, log_data_sector(), 1, (UCHAR *)&payload, 1);
    if (status != FX_SUCCESS)
    {
        return(status);
    }

    ram_disk.fx_media_fault_tolerant_file_size -= shortfall;

    return(_fx_fault_tolerant_transaction_end(&ram_disk));
}


/* Stage one directory log entry, then record a log size that leaves no room for
   the entries at all, and replay the log.  */
static UINT    replay_dir_log_recording(ULONG recorded)
{

UINT        status;
UINT        payload = 0;

    status =  media_prepare();
    if (status != FX_SUCCESS)
    {
        return(status);
    }

    _fx_fault_tolerant_transaction_start(&ram_disk);

    status =  _fx_fault_tolerant_add_dir_log(&ram_disk, log_data_sector(), 1, (UCHAR *)&payload, 1);
    if (status != FX_SUCCESS)
    {
        return(status);
    }

    ram_disk.fx_media_fault_tolerant_file_size = recorded;

    return(_fx_fault_tolerant_transaction_end(&ram_disk));
}


/* Stage one FAT log entry, then declare it shorter than a FAT log entry, and
   replay the log.  */
static UINT    replay_short_fat_log(VOID)
{

UINT                       status;
FX_FAULT_TOLERANT_FAT_LOG *fat_log;

    status =  media_prepare();
    if (status != FX_SUCCESS)
    {
        return(status);
    }

    _fx_fault_tolerant_transaction_start(&ram_disk);

    /* The next log entry lands at the current end of the log file.  */
    fat_log =  (FX_FAULT_TOLERANT_FAT_LOG *)(ram_disk.fx_media_fault_tolerant_memory_buffer +
                                             ram_disk.fx_media_fault_tolerant_file_size);

    status =  _fx_fault_tolerant_add_FAT_log(&ram_disk, ram_disk.fx_media_fault_tolerant_start_cluster,
                                             ram_disk.fx_media_fat_last);
    if (status != FX_SUCCESS)
    {
        return(status);
    }

    /* Declare one word less than the entry occupies.  */
    _fx_utility_16_unsigned_write((UCHAR *)&fat_log -> fx_fault_tolerant_FAT_log_size,
                                  FX_FAULT_TOLERANT_FAT_LOG_ENTRY_SIZE - 4);

    return(_fx_fault_tolerant_transaction_end(&ram_disk));
}


/* Rewrite the log file header on the media so it records total_size, keeping the
   header checksum valid, then enable fault tolerance over a buffer of
   buffer_size bytes.  */
static UINT    enable_over_log_recording(USHORT total_size, UINT buffer_size)
{

UINT                          status;
USHORT                        checksum;
ULONG64                       header_sector;
FX_FAULT_TOLERANT_LOG_HEADER *log_header;

    status =  media_prepare();
    if (status != FX_SUCCESS)
    {
        return(status);
    }

    /* The log file's location is only known while fault tolerance is enabled.  */
    header_sector =  log_header_sector();

    status =  fx_media_close(&ram_disk);
    if (status != FX_SUCCESS)
    {
        return(status);
    }

    status =  fx_media_open(&ram_disk, "RAM DISK", _fx_ram_driver, ram_disk_memory_large,
                            cache_buffer, CACHE_SIZE);
    if (status != FX_SUCCESS)
    {
        return(status);
    }

    /* Read the first sector of the log file, which carries the header.  */
    status =  _fx_utility_logical_sector_read(&ram_disk, header_sector,
                                              ram_disk.fx_media_memory_buffer,
                                              ((ULONG) 1), FX_DATA_SECTOR);
    if (status != FX_SUCCESS)
    {
        return(status);
    }

    log_header =  (FX_FAULT_TOLERANT_LOG_HEADER *)ram_disk.fx_media_memory_buffer;

    /* The header checksum covers its own field, so zero it before computing.  */
    _fx_utility_16_unsigned_write((UCHAR *)&log_header -> fx_fault_tolerant_log_header_total_size, total_size);
    _fx_utility_16_unsigned_write((UCHAR *)&log_header -> fx_fault_tolerant_log_header_checksum, 0);
    checksum =  _fx_fault_tolerant_calculate_checksum((UCHAR *)log_header, FX_FAULT_TOLERANT_LOG_HEADER_SIZE);
    _fx_utility_16_unsigned_write((UCHAR *)&log_header -> fx_fault_tolerant_log_header_checksum, checksum);

    status =  _fx_utility_logical_sector_write(&ram_disk, header_sector,
                                               ram_disk.fx_media_memory_buffer,
                                               ((ULONG) 1), FX_DIRECTORY_SECTOR);
    if (status != FX_SUCCESS)
    {
        return(status);
    }

    status =  _fx_utility_logical_sector_flush(&ram_disk, ((ULONG64) 0), ram_disk.fx_media_total_sectors, FX_TRUE);
    if (status != FX_SUCCESS)
    {
        return(status);
    }

    return(fx_fault_tolerant_enable(&ram_disk, fault_tolerant_buffer, buffer_size));
}


/* Define what the initial system looks like.  */

#ifdef CTEST
void test_application_define(void *first_unused_memory)
#else
void    filex_fault_tolerant_apply_logs_bounds_test_application_define(void *first_unused_memory)
#endif
{


#ifndef FX_STANDALONE_ENABLE
    /* Setup the working pointer.  */
    pointer =  (UCHAR *) first_unused_memory;

    /* Create the main thread.  */

    tx_thread_create(&ftest_0, "thread 0", ftest_0_entry, 0,
            pointer, DEMO_STACK_SIZE,
            4, 4, TX_NO_TIME_SLICE, TX_AUTO_START);

    pointer =  pointer + DEMO_STACK_SIZE;

    /* Setup memory for the RAM disk and the sector cache.  */
    cache_buffer =  pointer;
    pointer += CACHE_SIZE;
    fault_tolerant_buffer = pointer;
    pointer += FAULT_TOLERANT_BUFFER;
#endif

    /* Initialize the FileX system.  */
    fx_system_initialize();
#ifdef FX_STANDALONE_ENABLE
    ftest_0_entry(0);
#endif
}


/* Define the test threads.  */

static void    ftest_0_entry(ULONG thread_input)
{

UINT        status;
USHORT      total_size;

    FX_PARAMETER_NOT_USED(thread_input);

    /* Print out some test information banners.  */
    printf("FileX Test:   Fault Tolerant Apply Logs Bounds test..................");

    /* A copy that runs past the destination sector must be refused.  The sector
       staged at fx_media_memory_buffer is one sector wide, so an offset inside the
       cache allocation but past the sector is the case that used to be accepted.  */
    status =  replay_dir_log_at_offset(BYTES_PER_SECTOR + 44);
    return_if_fail( status == FX_FILE_CORRUPT);

    status =  fx_media_close(&ram_disk);
    return_if_fail( status == FX_SUCCESS);

    /* A copy that ends exactly on the sector boundary is still legal.  */
    status =  replay_dir_log_at_offset(BYTES_PER_SECTOR - 1);
    return_if_fail( status == FX_SUCCESS);

    status =  fx_media_close(&ram_disk);
    return_if_fail( status == FX_SUCCESS);

    /* A clean log file records no content beyond the header and the FAT chain, and
       enabling fault tolerance over one on a re-mounted media has to succeed.  */
    status =  media_prepare();
    return_if_fail( status == FX_SUCCESS);

    total_size =  (USHORT)_fx_utility_16_unsigned_read(ram_disk.fx_media_fault_tolerant_memory_buffer +
                                                       sizeof(ULONG));
    return_if_fail( total_size == FX_FAULT_TOLERANT_LOG_CONTENT_OFFSET);

    status =  fx_media_close(&ram_disk);
    return_if_fail( status == FX_SUCCESS);

    status =  fx_media_open(&ram_disk, "RAM DISK", _fx_ram_driver, ram_disk_memory_large,
                            cache_buffer, CACHE_SIZE);
    return_if_fail( status == FX_SUCCESS);

    status =  fx_fault_tolerant_enable(&ram_disk, fault_tolerant_buffer, FAULT_TOLERANT_SIZE);
    return_if_fail( status == FX_SUCCESS);

    status =  fx_media_close(&ram_disk);
    return_if_fail( status == FX_SUCCESS);

    /* A log entry may claim only the bytes that follow the header, the FAT chain
       and the content header.  The bound was computed from the content header
       alone, which left every entry free to claim the 36 bytes in front of it.  */
    status =  replay_dir_log_short_by(1);
    return_if_fail( status == FX_FILE_CORRUPT);

    status =  fx_media_close(&ram_disk);
    return_if_fail( status == FX_SUCCESS);

    /* A FAT log entry that declares less than one entry desynchronises the walk:
       the entry is consumed, the cursor advances by less than the entry occupies,
       and every entry behind it is then read from the middle of this one.  */
    status =  replay_short_fat_log();
    return_if_fail( status == FX_FILE_CORRUPT);

    status =  fx_media_close(&ram_disk);
    return_if_fail( status == FX_SUCCESS);

    /* A log file recording more bytes than the caller's buffer holds has to be
       refused.  fx_fault_tolerant_enable accepts any buffer of at least one
       sector, so a small buffer under a full-size log is reachable through the
       public API, and everything past this point indexes the buffer by the
       recorded size.  */
    status =  enable_over_log_recording(FX_FAULT_TOLERANT_MAXIMUM_LOG_FILE_SIZE, BYTES_PER_SECTOR * 2);
    return_if_fail( status == FX_FILE_CORRUPT);

    status =  fx_media_close(&ram_disk);
    return_if_fail( status == FX_SUCCESS);

    /* A log file that records less than the header, the FAT chain and the content
       header together leaves no room for any entry, and the replay has to refuse it
       before subtracting them from the recorded size.  */
    status =  replay_dir_log_recording(FX_FAULT_TOLERANT_LOG_CONTENT_OFFSET + 2);
    return_if_fail( status == FX_FILE_CORRUPT);

    status =  fx_media_close(&ram_disk);
    return_if_fail( status == FX_SUCCESS);

    /* A log recording less than a reset one writes is corrupt whatever the buffer.  */
    status =  enable_over_log_recording(FX_FAULT_TOLERANT_LOG_CONTENT_OFFSET - 1, FAULT_TOLERANT_SIZE);
    return_if_fail( status == FX_FILE_CORRUPT);

    status =  fx_media_close(&ram_disk);
    return_if_fail( status == FX_SUCCESS);

    /* So is one recording more than the format allows.  The buffer here is larger
       than the maximum on purpose: with a smaller one the buffer test refuses the
       log first and this condition is never reached.  */
    status =  enable_over_log_recording(FX_FAULT_TOLERANT_MAXIMUM_LOG_FILE_SIZE + 1, FAULT_TOLERANT_BUFFER);
    return_if_fail( status == FX_FILE_CORRUPT);

    status =  fx_media_close(&ram_disk);
    return_if_fail( status == FX_SUCCESS);

    /* Output successful.  */
    printf("SUCCESS!\n");
    test_control_return(0);
}

#else

#ifdef CTEST
void test_application_define(void *first_unused_memory)
#else
void    filex_fault_tolerant_apply_logs_bounds_test_application_define(void *first_unused_memory)
#endif
{

    FX_PARAMETER_NOT_USED(first_unused_memory);

    /* Print out some test information banners.  */
    printf("FileX Test:   Fault Tolerant Apply Logs Bounds test..................N/A\n");

    test_control_return(255);
}
#endif
