/***************************************************************************
 * Copyright (c) 2026 Eclipse ThreadX contributors
 * 
 * This program and the accompanying materials are made available under the
 * terms of the MIT License which is available at
 * https://opensource.org/licenses/MIT.
 * 
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 * 
 * SPDX-License-Identifier: MIT and CC0-1.0
 **************************************************************************/

/* This FileX test concentrates on _fx_partition_offset_calculate_extended -- the partition
   table parser that resolves a primary or extended partition to its starting sector and
   size, given a 512-byte table or boot sector.

   The test calls that function directly, and the disclosure that requires is this.  No
   FileX API reaches it: it is documented as "CALLED BY: Application Driver", and no
   configuration of this suite, and no shipped configuration of FileX, calls it.  Nor is it
   declared in any header -- not fx_api.h, not anything under common/inc, not the port
   header -- so an application driver that wants it has to declare the prototype itself,
   which is what this file does below and what filex_utility_test.c already does for the
   non-extended sibling in the same source file.

   Nothing is interposed.  No symbol is replaced and no FileX function is stubbed: the
   certified function runs its own code end to end.  The media control block it is handed
   is one fx_media_open produced, field for field, and the driver behind it is the
   regression suite's own RAM driver -- so the chained reads at :534 are served by the
   ordinary application-supplied driver contract rather than by anything built to answer
   them.  The one read that fails is failed by that driver, through the selective error
   injection the suite already uses elsewhere, which is the failure every block medium has.

   Two properties of the function shape the test and are worth stating, because both are
   easy to trip over.  It reads each chained partition table sector into the *caller's own
   buffer*, so the buffer must be rebuilt before every call.  And it writes seven driver
   request fields and fx_media_hidden_sectors itself before each chained read, so the only
   field of the media it takes from the caller is fx_media_driver_entry; the media is
   formatted with zero hidden sectors, which is what every media in this suite has, so the
   write at :531 leaves it unchanged.

   The test asserts in all eleven build configurations and has no N/A arm.  The file
   compiles identically in every one of them -- it contains no feature gate at all.  */

#ifndef FX_STANDALONE_ENABLE
#include   "tx_api.h"
#endif
#include   "fx_api.h"
#include   "fx_ram_driver_test.h"
#include   <stdio.h>
#include   <string.h>

void  test_control_return(UINT status);
void  filex_partition_offset_extended_application_define(void *first_unused_memory);

/* No header declares the partition table utilities, so a caller declares them itself.  */

UINT  _fx_partition_offset_calculate_extended(FX_MEDIA *media_ptr, void *partition_sector, UINT partition,
                                              ULONG *partition_start, ULONG *partition_size);

VOID  _fx_ram_driver(FX_MEDIA *media_ptr);


#define     DEMO_STACK_SIZE         4096
#define     SECTOR_SIZE             512
#define     TOTAL_SECTORS           256
#define     CACHE_SIZE              (SECTOR_SIZE * 16)

/* The two sectors the extended chain is built at.  Both are inside the media and outside
   everything the format writes, and nothing but the chain walk ever reads them.  */

#define     CHAIN_SECTOR_1          128
#define     CHAIN_SECTOR_2          160

/* Partition table layout, as the function reads it.  */

#define     TABLE_OFFSET            446
#define     ENTRY_SIZE              16
#define     ENTRY_TYPE_OFFSET       4
#define     ENTRY_LBA_OFFSET        8
#define     ENTRY_SECTORS_OFFSET    12

#define     TYPE_FREE               0x00
#define     TYPE_FAT32_LBA          0x0C
#define     TYPE_EXTENDED           0x05
#define     TYPE_EXTENDED_LBA       0x0F

/* The partition each chain link describes, and the primary partition of the simple case.
   The values are arbitrary and are asserted on, so a wrong link is a failed assertion
   rather than a silently different answer.  */

#define     PRIMARY_LBA             0x00000020
#define     PRIMARY_SECTORS         0x0000A5A5
#define     LINK_1_LBA              0x00000004
#define     LINK_1_SECTORS          0x00001122
#define     LINK_2_LBA              0x00000008
#define     LINK_2_SECTORS          0x00003344


/* Define the ThreadX and FileX object control blocks...  */

#ifndef FX_STANDALONE_ENABLE
static TX_THREAD               ftest_0;
#endif
static FX_MEDIA                ram_disk;


/* Define the counters used in the test application...  */

#ifndef FX_STANDALONE_ENABLE
static UCHAR                  *cache_buffer;
#else
static UCHAR                   cache_buffer[CACHE_SIZE];
#endif

/* The buffer handed to the function, rebuilt before every call.  */

static UCHAR                   partition_buffer[SECTOR_SIZE];


/* Define thread prototypes.  */

static void    ftest_0_entry(ULONG thread_input);


/* Define what the initial system looks like.  */

#ifdef CTEST
void test_application_define(void *first_unused_memory)
#else
void    filex_partition_offset_extended_application_define(void *first_unused_memory)
#endif
{

#ifndef FX_STANDALONE_ENABLE
UCHAR    *pointer;


    /* Setup the working pointer.  */
    pointer =  (UCHAR *) first_unused_memory;

    /* Create the main thread.  */
    tx_thread_create(&ftest_0, "thread 0", ftest_0_entry, 0,  
            pointer, DEMO_STACK_SIZE, 
            4, 4, TX_NO_TIME_SLICE, TX_AUTO_START);

    pointer =  pointer + DEMO_STACK_SIZE;

    /* Setup memory for the sector cache.  The RAM disk uses ram_disk_memory_large, so that
       the chain sectors can be laid into it at a fixed offset.  */
    cache_buffer =  pointer;

#else
    FX_PARAMETER_NOT_USED(first_unused_memory);
#endif

    /* Initialize the FileX system.  */
    fx_system_initialize();
#ifdef FX_STANDALONE_ENABLE
    ftest_0_entry(0);
#endif
}


/* Write a partition table entry into a 512-byte buffer, little endian as the parser
   reads it.  */

static void    set_entry(UCHAR *buffer, UINT slot, UCHAR type, ULONG lba, ULONG sectors)
{

UINT     offset;


    offset =  TABLE_OFFSET + slot * ENTRY_SIZE;

    buffer[offset + ENTRY_TYPE_OFFSET] =       type;

    buffer[offset + ENTRY_LBA_OFFSET] =        (UCHAR)(lba & 0xFF);
    buffer[offset + ENTRY_LBA_OFFSET + 1] =    (UCHAR)((lba >> 8) & 0xFF);
    buffer[offset + ENTRY_LBA_OFFSET + 2] =    (UCHAR)((lba >> 16) & 0xFF);
    buffer[offset + ENTRY_LBA_OFFSET + 3] =    (UCHAR)((lba >> 24) & 0xFF);

    buffer[offset + ENTRY_SECTORS_OFFSET] =     (UCHAR)(sectors & 0xFF);
    buffer[offset + ENTRY_SECTORS_OFFSET + 1] = (UCHAR)((sectors >> 8) & 0xFF);
    buffer[offset + ENTRY_SECTORS_OFFSET + 2] = (UCHAR)((sectors >> 16) & 0xFF);
    buffer[offset + ENTRY_SECTORS_OFFSET + 3] = (UCHAR)((sectors >> 24) & 0xFF);
}


/* Clear a buffer to an otherwise empty partition table carrying a valid signature.  */

static void    build_empty_table(UCHAR *buffer)
{

    memset(buffer, 0, SECTOR_SIZE);
    buffer[510] =  FX_SIG_BYTE_1;
    buffer[511] =  FX_SIG_BYTE_2;
}


/* Lay a sector into the RAM disk's backing store, where the RAM driver will find it when
   the chain walk asks for that sector.  */

static void    place_sector(ULONG sector, UCHAR *buffer)
{

    memcpy(&ram_disk_memory_large[sector * SECTOR_SIZE], buffer, SECTOR_SIZE);
}


/* The boot-sector prologue, as a table.  Every row differs only in the bytes the two
   leading tests read: the jump instruction at 0 and 2, which of the six sectors-per-FAT
   bytes is non-zero, and the two total-sector fields.  A row with no total sector count
   falls through to the signature check and out through the free primary slot, which is
   why every fall-through row expects FX_NOT_FOUND.  */

typedef struct BOOT_VARIANT_STRUCT
{
    UCHAR   boot_byte_0;
    UCHAR   boot_byte_2;
    UINT    sectors_per_fat_offset;     /* 0 leaves all six bytes zero.  */
    ULONG   sectors_16;                 /* FX_SECTORS, read as a USHORT.  */
    ULONG   sectors_32;                 /* FX_HUGE_SECTORS, read as a ULONG.  */
    UINT    expected_status;
    ULONG   expected_size;
} BOOT_VARIANT;

static BOOT_VARIANT  boot_variants[] =
{
    /* A boot sector in the one-byte form, with a FAT12/16 sector count.  */
    {0xe9, 0x00, 0x16, 0x00001234, 0x00000000, FX_SUCCESS,   0x00001234},

    /* The two-byte form, with no FAT12/16 count so the FAT32 field is read instead.  */
    {0xeb, 0x90, 0x17, 0x00000000, 0x00ABCDEF, FX_SUCCESS,   0x00ABCDEF},

    /* The two-byte form with the wrong second byte -- not a boot sector.  */
    {0xeb, 0x00, 0x16, 0x00001234, 0x00000000, FX_NOT_FOUND, 0},

    /* Neither form -- not a boot sector.  */
    {0x00, 0x00, 0x16, 0x00001234, 0x00000000, FX_NOT_FOUND, 0},

    /* The remaining four sectors-per-FAT bytes, one row each.  */
    {0xe9, 0x00, 0x24, 0x00001234, 0x00000000, FX_SUCCESS,   0x00001234},
    {0xe9, 0x00, 0x25, 0x00001234, 0x00000000, FX_SUCCESS,   0x00001234},
    {0xe9, 0x00, 0x26, 0x00001234, 0x00000000, FX_SUCCESS,   0x00001234},
    {0xe9, 0x00, 0x27, 0x00001234, 0x00000000, FX_SUCCESS,   0x00001234},

    /* No sectors-per-FAT value at all -- not a usable boot sector.  */
    {0xe9, 0x00, 0x00, 0x00001234, 0x00000000, FX_NOT_FOUND, 0},

    /* Sectors per FAT, but neither total sector field carries a count.  */
    {0xe9, 0x00, 0x16, 0x00000000, 0x00000000, FX_NOT_FOUND, 0}
};

#define BOOT_VARIANT_COUNT  (sizeof(boot_variants) / sizeof(BOOT_VARIANT))


/* Build the buffer a boot variant describes.  The partition table underneath it is empty
   with a valid signature, so a row that is not a boot sector resolves partition 0 to a
   free slot.  */

static void    build_boot_variant(BOOT_VARIANT *variant)
{

    build_empty_table(partition_buffer);

    partition_buffer[0] =  variant -> boot_byte_0;
    partition_buffer[2] =  variant -> boot_byte_2;

    if (variant -> sectors_per_fat_offset)
    {
        partition_buffer[variant -> sectors_per_fat_offset] =  1;
    }

    partition_buffer[FX_SECTORS] =           (UCHAR)(variant -> sectors_16 & 0xFF);
    partition_buffer[FX_SECTORS + 1] =       (UCHAR)((variant -> sectors_16 >> 8) & 0xFF);

    partition_buffer[FX_HUGE_SECTORS] =      (UCHAR)(variant -> sectors_32 & 0xFF);
    partition_buffer[FX_HUGE_SECTORS + 1] =  (UCHAR)((variant -> sectors_32 >> 8) & 0xFF);
    partition_buffer[FX_HUGE_SECTORS + 2] =  (UCHAR)((variant -> sectors_32 >> 16) & 0xFF);
    partition_buffer[FX_HUGE_SECTORS + 3] =  (UCHAR)((variant -> sectors_32 >> 24) & 0xFF);
}


/* Build a partition table whose first extended slot points at the chain, and lay the two
   chain sectors into the RAM disk.  The caller says what the chain looks like.  */

static void    build_chain(UCHAR extended_type, UINT extended_slot,
                           UCHAR link_1_type, UCHAR link_1_next_type,
                           UCHAR link_1_signature_0, UCHAR link_1_signature_1)
{

UCHAR    chain_sector[SECTOR_SIZE];


    /* The table handed to the function: the extended partition sits in the nominated
       slot and every earlier slot holds an ordinary FAT32 partition.  */
    build_empty_table(partition_buffer);
    if (extended_slot > 0)
    {
        set_entry(partition_buffer, 0, TYPE_FAT32_LBA, PRIMARY_LBA, PRIMARY_SECTORS);
    }
    set_entry(partition_buffer, extended_slot, extended_type, CHAIN_SECTOR_1, 0);

    /* The first link: its own first entry is partition 4, its second entry points at the
       next link, relative to the extended partition's own base sector.  */
    build_empty_table(chain_sector);
    chain_sector[510] =  link_1_signature_0;
    chain_sector[511] =  link_1_signature_1;
    set_entry(chain_sector, 0, link_1_type, LINK_1_LBA, LINK_1_SECTORS);
    if (link_1_next_type != TYPE_FREE)
    {
        set_entry(chain_sector, 1, link_1_next_type, CHAIN_SECTOR_2 - CHAIN_SECTOR_1, 0);
    }
    place_sector(CHAIN_SECTOR_1, chain_sector);

    /* The second link: its first entry is partition 5, and it ends the chain.  */
    build_empty_table(chain_sector);
    set_entry(chain_sector, 0, TYPE_FAT32_LBA, LINK_2_LBA, LINK_2_SECTORS);
    place_sector(CHAIN_SECTOR_2, chain_sector);
}


/* Define the test threads.  */

static void    ftest_0_entry(ULONG thread_input)
{

UINT        status;
UINT        i;
ULONG       partition_start;
ULONG       partition_size;
ULONG       hidden_sectors;

    FX_PARAMETER_NOT_USED(thread_input);

    /* Print out some test information banners.  */
    printf("FileX Test:   Partition offset extended test.........................");

    /* Format the media.  This needs to be done before opening it!  The sector size is 512
       because the partition table the function parses is a 512-byte sector, and the chain
       sectors are laid into the backing store at that stride.  */
    status =  fx_media_format(&ram_disk, 
                            _fx_ram_driver,         // Driver entry
                            ram_disk_memory_large,  // RAM disk memory pointer
                            cache_buffer,           // Media buffer pointer
                            CACHE_SIZE,             // Media buffer size 
                            "MY_RAM_DISK",          // Volume Name
                            1,                      // Number of FATs
                            32,                     // Directory Entries
                            0,                      // Hidden sectors
                            TOTAL_SECTORS,          // Total sectors 
                            SECTOR_SIZE,            // Sector size   
                            1,                      // Sectors per cluster
                            1,                      // Heads
                            1);                     // Sectors per track 
    return_value_if_fail(status == FX_SUCCESS, 1);

    /* Open the RAM disk.  Every call below is handed this media control block, which is
       the one fx_media_open built.  */
    status =  fx_media_open(&ram_disk, "RAM DISK", _fx_ram_driver, ram_disk_memory_large, cache_buffer, CACHE_SIZE);
    return_value_if_fail(status == FX_SUCCESS, 2);
    return_value_if_fail(ram_disk.fx_media_bytes_per_sector == SECTOR_SIZE, 3);

    hidden_sectors =  (ULONG) ram_disk.fx_media_hidden_sectors;

    /* The boot-sector prologue, once with somewhere to put the answer and once without.
       Both passes assert the status; the first also asserts the size, which is the value
       the prologue exists to produce.  */
    for (i = 0; i < BOOT_VARIANT_COUNT; i++)
    {

        build_boot_variant(&boot_variants[i]);
        partition_start =  0xFFFFFFFF;
        partition_size =   0xFFFFFFFF;
        status =  _fx_partition_offset_calculate_extended(&ram_disk, partition_buffer, 0,
                                                          &partition_start, &partition_size);
        return_value_if_fail(status == boot_variants[i].expected_status, 40 + i);
        if (boot_variants[i].expected_status == FX_SUCCESS)
        {

            /* A boot sector starts at zero and is as long as its own sector count.  */
            return_value_if_fail(partition_start == 0, 60 + i);
            return_value_if_fail(partition_size == boot_variants[i].expected_size, 80 + i);
        }

        build_boot_variant(&boot_variants[i]);
        status =  _fx_partition_offset_calculate_extended(&ram_disk, partition_buffer, 0,
                                                          FX_NULL, FX_NULL);
        return_value_if_fail(status == boot_variants[i].expected_status, 100 + i);
    }

    /* A buffer that is neither a boot sector nor a partition table.  Each signature byte
       is wrong on its own, because the check reads them in order.  */
    build_empty_table(partition_buffer);
    partition_buffer[510] =  0x00;
    status =  _fx_partition_offset_calculate_extended(&ram_disk, partition_buffer, 0,
                                                      &partition_start, &partition_size);
    return_value_if_fail(status == FX_NOT_FOUND, 8);

    build_empty_table(partition_buffer);
    partition_buffer[511] =  0x00;
    status =  _fx_partition_offset_calculate_extended(&ram_disk, partition_buffer, 0,
                                                      &partition_start, &partition_size);
    return_value_if_fail(status == FX_NOT_FOUND, 9);

    /* A primary partition in use, resolved from the table alone with no media access.  */
    build_empty_table(partition_buffer);
    set_entry(partition_buffer, 2, TYPE_FAT32_LBA, PRIMARY_LBA, PRIMARY_SECTORS);
    partition_start =  0xFFFFFFFF;
    partition_size =   0xFFFFFFFF;
    status =  _fx_partition_offset_calculate_extended(&ram_disk, partition_buffer, 2,
                                                      &partition_start, &partition_size);
    return_value_if_fail(status == FX_SUCCESS, 10);
    return_value_if_fail(partition_start == PRIMARY_LBA, 11);
    return_value_if_fail(partition_size == PRIMARY_SECTORS, 12);

    /* The same primary partition with nowhere to put either answer.  */
    build_empty_table(partition_buffer);
    set_entry(partition_buffer, 2, TYPE_FAT32_LBA, PRIMARY_LBA, PRIMARY_SECTORS);
    status =  _fx_partition_offset_calculate_extended(&ram_disk, partition_buffer, 2,
                                                      FX_NULL, FX_NULL);
    return_value_if_fail(status == FX_SUCCESS, 13);

    /* A partition index past the parameter clamp.  FX_MAX_PARTITION_COUNT self-defaults
       to 16 in the source, so 17 is the first index it refuses.  */
    build_empty_table(partition_buffer);
    status =  _fx_partition_offset_calculate_extended(&ram_disk, partition_buffer, 17,
                                                      &partition_start, &partition_size);
    return_value_if_fail(status == FX_NOT_FOUND, 14);

    /* An extended partition asked for on a table that has none: all four primary slots
       hold ordinary partitions, so the scan runs out.  */
    build_empty_table(partition_buffer);
    for (i = 0; i < 4; i++)
    {
        set_entry(partition_buffer, i, TYPE_FAT32_LBA, PRIMARY_LBA, PRIMARY_SECTORS);
    }
    status =  _fx_partition_offset_calculate_extended(&ram_disk, partition_buffer, 4,
                                                      &partition_start, &partition_size);
    return_value_if_fail(status == FX_NOT_FOUND, 15);

    /* The first link of the extended chain, read from the media through the driver.  The
       starting sector is the link's own offset plus the chain's base sector, which is
       what distinguishes a chain walk from a primary lookup.  */
    build_chain(TYPE_EXTENDED, 0, TYPE_FAT32_LBA, TYPE_FREE, FX_SIG_BYTE_1, FX_SIG_BYTE_2);
    partition_start =  0xFFFFFFFF;
    partition_size =   0xFFFFFFFF;
    status =  _fx_partition_offset_calculate_extended(&ram_disk, partition_buffer, 4,
                                                      &partition_start, &partition_size);
    return_value_if_fail(status == FX_SUCCESS, 16);
    return_value_if_fail(partition_start == LINK_1_LBA + CHAIN_SECTOR_1, 17);
    return_value_if_fail(partition_size == LINK_1_SECTORS, 18);

    /* The chained read writes seven driver request fields and the media's hidden sector
       count.  A media formatted with no hidden sectors is left as it was.  */
    return_value_if_fail((ULONG) ram_disk.fx_media_hidden_sectors == hidden_sectors, 19);

    /* The same link with nowhere to put either answer.  */
    build_chain(TYPE_EXTENDED, 0, TYPE_FAT32_LBA, TYPE_FREE, FX_SIG_BYTE_1, FX_SIG_BYTE_2);
    status =  _fx_partition_offset_calculate_extended(&ram_disk, partition_buffer, 4,
                                                      FX_NULL, FX_NULL);
    return_value_if_fail(status == FX_SUCCESS, 20);

    /* The extended slot found in the second primary slot rather than the first, and
       carrying the LBA type code.  Both are read by the same scan.  */
    build_chain(TYPE_EXTENDED_LBA, 1, TYPE_FAT32_LBA, TYPE_FREE, FX_SIG_BYTE_1, FX_SIG_BYTE_2);
    partition_start =  0xFFFFFFFF;
    partition_size =   0xFFFFFFFF;
    status =  _fx_partition_offset_calculate_extended(&ram_disk, partition_buffer, 4,
                                                      &partition_start, &partition_size);
    return_value_if_fail(status == FX_SUCCESS, 21);
    return_value_if_fail(partition_start == LINK_1_LBA + CHAIN_SECTOR_1, 22);

    /* A chain link whose partition slot is free.  */
    build_chain(TYPE_EXTENDED, 0, TYPE_FREE, TYPE_FREE, FX_SIG_BYTE_1, FX_SIG_BYTE_2);
    status =  _fx_partition_offset_calculate_extended(&ram_disk, partition_buffer, 4,
                                                      &partition_start, &partition_size);
    return_value_if_fail(status == FX_NOT_FOUND, 23);

    /* A chain link that is not a partition table.  Each signature byte again on its own.  */
    build_chain(TYPE_EXTENDED, 0, TYPE_FAT32_LBA, TYPE_FREE, 0x00, FX_SIG_BYTE_2);
    status =  _fx_partition_offset_calculate_extended(&ram_disk, partition_buffer, 4,
                                                      &partition_start, &partition_size);
    return_value_if_fail(status == FX_NOT_FOUND, 24);

    build_chain(TYPE_EXTENDED, 0, TYPE_FAT32_LBA, TYPE_FREE, FX_SIG_BYTE_1, 0x00);
    status =  _fx_partition_offset_calculate_extended(&ram_disk, partition_buffer, 4,
                                                      &partition_start, &partition_size);
    return_value_if_fail(status == FX_NOT_FOUND, 25);

    /* The chained read failed by the driver.  The count is asserted as well as the status,
       because a chain sector served from anywhere but the driver would leave it at zero.  */
    build_chain(TYPE_EXTENDED, 0, TYPE_FAT32_LBA, TYPE_FREE, FX_SIG_BYTE_1, FX_SIG_BYTE_2);
    _fx_ram_driver_io_error_select_count =    0;
    _fx_ram_driver_io_error_select_request =  FX_DRIVER_READ;
    _fx_ram_driver_io_error_select_sector =   CHAIN_SECTOR_1;
    _fx_ram_driver_io_error_select =          FX_TRUE;
    status =  _fx_partition_offset_calculate_extended(&ram_disk, partition_buffer, 4,
                                                      &partition_start, &partition_size);
    return_value_if_fail(status == FX_IO_ERROR, 26);
    return_value_if_fail(_fx_ram_driver_io_error_select_count == 1, 27);
    return_value_if_fail(_fx_ram_driver_io_error_select == FX_FALSE, 28);

    /* The second link of the chain, reached by following the first link's own second
       entry.  Its starting sector is relative to the second link's sector, so a walk that
       stopped early or mis-added the base would not produce this value.  */
    build_chain(TYPE_EXTENDED, 0, TYPE_FAT32_LBA, TYPE_EXTENDED, FX_SIG_BYTE_1, FX_SIG_BYTE_2);
    partition_start =  0xFFFFFFFF;
    partition_size =   0xFFFFFFFF;
    status =  _fx_partition_offset_calculate_extended(&ram_disk, partition_buffer, 5,
                                                      &partition_start, &partition_size);
    return_value_if_fail(status == FX_SUCCESS, 29);
    return_value_if_fail(partition_start == LINK_2_LBA + CHAIN_SECTOR_2, 30);
    return_value_if_fail(partition_size == LINK_2_SECTORS, 31);

    /* The same walk with the next link carrying the LBA type code.  */
    build_chain(TYPE_EXTENDED, 0, TYPE_FAT32_LBA, TYPE_EXTENDED_LBA, FX_SIG_BYTE_1, FX_SIG_BYTE_2);
    partition_start =  0xFFFFFFFF;
    status =  _fx_partition_offset_calculate_extended(&ram_disk, partition_buffer, 5,
                                                      &partition_start, &partition_size);
    return_value_if_fail(status == FX_SUCCESS, 32);
    return_value_if_fail(partition_start == LINK_2_LBA + CHAIN_SECTOR_2, 33);

    /* A chain that ends before the requested partition: the first link has no next link.  */
    build_chain(TYPE_EXTENDED, 0, TYPE_FAT32_LBA, TYPE_FREE, FX_SIG_BYTE_1, FX_SIG_BYTE_2);
    status =  _fx_partition_offset_calculate_extended(&ram_disk, partition_buffer, 5,
                                                      &partition_start, &partition_size);
    return_value_if_fail(status == FX_NOT_FOUND, 34);

    /* The media survived every one of them.  */
    status =  fx_media_close(&ram_disk);
    return_value_if_fail(status == FX_SUCCESS, 35);

    /* Successful test.  */
    printf("SUCCESS!\n");
    test_control_return(0);
}
